### ISSUE TITLE
Make wrk directory configurable in baseline scan

### ISSUE THREAD

**Issue by sshniro** [zaproxy/zaproxy#5871]
When integrating the ZAP baseline scan with Github actions, I face two limitations.
1. Permission Issue: Github actions does not allow to start and persist the output file as it sets the work dir automatically.
`--workdir /__w/actions-test-repo/actions-test-repo`
for this, I'm switching the user to root when the container spins up.

2. Cannot persist report.
The volume is not getting mounted properly as pointed in the official documents and acknowledged by several issues. Github by default mounts 3 directories with the prefix of github/ . I was able to produce the report successfully by modifying the baseline scan to persist the files in github/home directory. 

To fix the second issue we can make the work directory configurable in the baseline script. Currently, it is hardcoded to zap/wrk inside the script.

The following is the final working configuration. It scans the example.com and produces the xml file for further processing.
https://github.com/sshniro/actions-test-repo/runs/443109463?check_suite_focus=true

The following is the docker init command.
![image](https://user-images.githubusercontent.com/13045528/74937934-5feddc80-53ed-11ea-9bb3-9ad9187dd36d.png)

**Comment by thc202** [comment]
Did you try bind the [workspace dir](https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context) to `/zap/wrk/` (e.g. `-v ${{ github.workspace }}:/zap/wrk/:rw`)? I'd expect that to work (both to read the configuration in the repo and save/process the reports).

**Comment by sshniro** [comment]
No, but I have hardcoded and tried this earlier. The following build is using the suggested configurations, but as you can see it has permission issues and cannot start ZAP. 
https://github.com/sshniro/actions-test-repo/runs/475249352?check_suite_focus=true

And this is the result when I add the user root parameter, it starts but it cannot persist the file.
https://github.com/sshniro/actions-test-repo/runs/475262713?check_suite_focus=true

**Comment by thc202** [comment]
Right, the `root` is required since by default the image uses the `zap` user but the volume should work. Mind trying with `owasp/zap2docker-stable` (and without `-v /var/run/docker.sock:/var/run/docker.sock`) ?

The following works fine:
```
name: ZAP
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
    steps:
      - run: pwd && ls -l
      - name: run zap baseline scan
        run: zap-baseline.py -t https://example.com -x report_xml.xml || echo 0
      - run: pwd && ls -l /zap/wrk/
```
