### ISSUE TITLE
DaemonBootstrap - Unsupported option

### ISSUE THREAD

**Issue by namloc2001** [zaproxy/zaproxy#5904]
**Describe the bug**
When deploying owasp/zap2docker-stable to OpenShift, using Helm with the following:
```
      containers:
      - name: kube-owasp-zap
        image: "owasp/zap2docker-stable:latest"
        imagePullPolicy: IfNotPresent
        command: ["zap.sh"]
        args: ["-daemon","-config api.addrs.addr.name=.*","-config api.addrs.addr.regex=true","-config api.key=abcd1234"]
```

and also experienced when specifying `host 0.0.0.0` and `port 8080` the logs return with "unsupported option..." it always seems to be the first argument to follow `-daemon`.

**To Reproduce**
Create Helm charts, deploy to OpenShift. with `helm install owaspzap <directory>`
View logs with `oc logs <pod_name>`

**Expected behavior**
I presume "unsupported option" shouldn't be encountered.

**Screenshots**

When specifying all arguments shown above:
![image](https://user-images.githubusercontent.com/30868661/76991021-d4f6f800-6940-11ea-867d-4f500d787cbd.png)

When not specifying `host 0.0.0.0`
![image](https://user-images.githubusercontent.com/30868661/76990926-a8db7700-6940-11ea-910d-82bc40932034.png)

when not specifying `host 0.0.0.0` or `port 8080`
![image](https://user-images.githubusercontent.com/30868661/76990036-38802600-693f-11ea-80f3-310504392be3.png)

**Software versions**
 - ZAP: latest
 - Add-on: N/A
 - OS: OpenShift on Red Hat
 - Java: don't have access to this.
 - Browser: N/A

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Would you like to help fix this issue?**
Yes please.
