### ISSUE TITLE
scanAsUser fails with missing_parameter when forced user in used

### ISSUE THREAD

**Issue by copethomas** [zaproxy/zaproxy#6458]
**Describe the bug**
I am running the ` zap-baseline.py` script within a K8s job using a context and a forced user however, when I run the script it errors with a `missing_parameter` because the `target` is not defined by the ` zap-baseline.py` script. The ZAP HTTP endpoint appears to mark this parameter as optional but in practice it appears to be required.  

**To Reproduce**
K8s Job

<details>
  <summary>click to expand</summary>
 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scanner
spec:
  template:
    spec:
      containers:
      - name: zap-scanner
        image: owasp/zap2docker-stable:latest
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "cp /zap-config/zap* /zap/wrk/ ; zap-baseline.py -m 3 -j -c zap-ignore-list -p zap-progress-list -n zap-context -U tomtest -t https://frontend:443 ; true"]
        volumeMounts:
        - name: zap-scanner-context
          mountPath: /zap-config/
        - name: zap-data
          mountPath: /zap/wrk
      volumes:
        - name: zap-data
          emptyDir: {}
        - name: zap-scanner-context
          configMap:
            name: zap-scanner-context
      restartPolicy: Never
  backoffLimit: 1
  parallelism: 1
  completions: 1
``` 
 
</details>

ZAP Context

<details>
  <summary>click to expand</summary>
 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
    <context>
        <name>test_site</name>
        <desc/>
        <inscope>true</inscope>
        <incregexes>https://frontend:443.*</incregexes>
	<excregexes>https://frontend:443/login</excregexes>
	<excregexes>https://frontend:443/logout</excregexes>
        <tech>
            <include>Db</include>
            <include>Db.CouchDB</include>
            <include>Db.Firebird</include>
            <include>Db.HypersonicSQL</include>
            <include>Db.IBM DB2</include>
            <include>Db.Microsoft Access</include>
            <include>Db.Microsoft SQL Server</include>
            <include>Db.MongoDB</include>
            <include>Db.MySQL</include>
            <include>Db.Oracle</include>
            <include>Db.PostgreSQL</include>
            <include>Db.SAP MaxDB</include>
            <include>Db.SQLite</include>
            <include>Db.Sybase</include>
            <include>Language</include>
            <include>Language.ASP</include>
            <include>Language.C</include>
            <include>Language.JSP/Servlet</include>
            <include>Language.Java</include>
            <include>Language.JavaScript</include>
            <include>Language.PHP</include>
            <include>Language.Python</include>
            <include>Language.Ruby</include>
            <include>Language.XML</include>
            <include>OS</include>
            <include>OS.Linux</include>
            <include>OS.MacOS</include>
            <include>OS.Windows</include>
            <include>SCM</include>
            <include>SCM.Git</include>
            <include>SCM.SVN</include>
            <include>WS</include>
            <include>WS.Apache</include>
            <include>WS.IIS</include>
            <include>WS.Tomcat</include>
        </tech>
        <urlparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </urlparser>
        <postparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </postparser>
        <authentication>
            <type>5</type>
            <loggedout>HTTP/1.1 401 Unauthorized</loggedout>
            <form>
                <loginurl>https://frontend:443/login</loginurl>
                <loginbody>{"user":"{%username%}","pass":"{%password%}"}</loginbody>
                <loginpageurl>https://frontend:443/login</loginpageurl>
            </form>
        </authentication>
        <users>
            <user>2754;true;dG9tdGVzdA==;5;redacted~</user>
        </users>
        <forceduser>2754</forceduser>
        <session>
            <type>0</type>
        </session>
        <authorization>
            <type>0</type>
            <basic>
                <header/>
                <body/>
                <logic>OR</logic>
                <code>401</code>
            </basic>
        </authorization>
    </context>
</configuration>

``` 

Error Message:

```
13726 [ZAP-ProxyThread-8] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/spider/action/scanAsUser/] from [127.0.0.1]:
org.zaproxy.zap.extension.api.ApiException: missing_parameter
	at org.zaproxy.zap.extension.spider.SpiderAPI.scanURL(SpiderAPI.java:493) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.spider.SpiderAPI.handleApiAction(SpiderAPI.java:284) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:507) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:497) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```
 
</details>

**Expected behavior**
ZAP to scan the endpoint using the force user and to authenticate against the login endpoint

**Screenshots**
n/a - Please see above

**Software versions**
 - ZAP: Latest owasp/zap2docker-stable container 
 - Add-on: n/a
 - OS: Linux (Docker)
 - Java: Bundled with official owasp/zap2docker-stable container 
 - Browser: None - Headless

**Additional context**
I am currently using this which appears to fix the issue:

```
command: [ "/bin/sh", "-c", "sed -i '406s/)/,target)/g' /zap/zap_common.py ; cp /zap-config/zap* /zap/wrk/ ; zap-baseline.py -m 3 -j -c zap-ignore-list -p zap-progress-list -n zap-context -U tomtest -t https://frontend:443 ; true"]

```

**Would you like to help fix this issue?**
I have raised: https://github.com/zaproxy/zaproxy/pull/6449 to fix the issue
