### ISSUE TITLE
Open API Specification - Not Accepting String Patterns & Array

### ISSUE THREAD

**Issue by sonawanesarvesh** [zaproxy/zaproxy#6487]
My Open API Specification contains Date & Array

 ```
parameters:
    tickerSymbolQuery:
        name: ticker-symbol
        in: query
        description: 'A ticker symbol is an arrangement of characters. Usually letters. Representing particular currencies. We can use it beyond just currencies. Eg. USDCOP.'
        required: false
        type: array
        items:
            type: string
            maxLength: 6
    uniqueIdentifierTypeQuery:
        name: unique-identifier-type
        in: query
        description: 'Unique identification code used to identify security exchange. Eg. FIGI'
        required: false
        type: string
        maxLength: 6
    uniqueIdentifierCodeQuery:
        name: unique-identifier-code
        in: query
        description: 'Unique identifier that identifies currencies as well as individual exchanges on which they trade. It is a 15-character alpha-numerical code that serves for uniform unique global identification. Eg. BBG0013HS3L6'
        required: false
        type: string
        maxLength: 15
    rateSourceQuery:
        name: rate-source
        in: query
        description: 'Source of the rate e.g. central bank, private banks, CITI, JP Morgan etc. Eg. TRM'
        required: false
        type: string
        maxLength: 10
    rateDateQuery:
        name: rate-date
        in: query
        description: 'This is used to retrieve the rates for a date in the past, i.e. historical rates (maximum of 36 months). It is not required for the current date''s rate. Date format should be MM/dd/yyyy. The Bloomberg time zone is GMT. E.g. 10/01/2019'
        required: false
        type: string
        format: date
        minLength: 10
        maxLength: 10
        pattern: ^(\d{2}/\d{2}/\d{4})$
    toDateQuery:
        name: to-date
        in: query
        description: 'This is used to retrieve the rates for a date in the past, i.e. historical rates (maximum of 36 months). It is not required for the current date''s rate. Date format should be MM/dd/yyyy. The Bloomberg time zone is GMT. E.g. 10/01/2019'
        required: true
        type: string
        format: date
        minLength: 10
        maxLength: 10
        pattern: ^(\d{2}/\d{2}/\d{4})$
    fromDateQuery:
        name: from-date
        in: query
        description: 'This is used to retrieve the rates for a date in the past, i.e. historical rates (maximum of 36 months). It is not required for the current date''s rate. Date format should be MM/dd/yyyy. The Bloomberg time zone is GMT. E.g. 10/01/2019'
        required: true
        type: string
        format: date
        minLength: 10
        maxLength: 10
        pattern: ^(\d{2}/\d{2}/\d{4})$
    priceTypeQuery:
        name: price-type
        in: query
        description: 'Type of daily exchange rate e.g. Daily sale, Daily buy, Daily average etc. Eg. ASK'
        required: false
        type: string
        enum:
            - ASK
            - BID
            - HIGH
            - LOW
            - LAST
            - '*'
    pageNumberQuery:
        name: page-number
        in: query
        description: 'page number'
        required: false
        type: integer
        format: int32
```

But i see ZAP Spider and Active Scanner is not able to understand it correctly, and in query it not getting reflected correctly

Check below sample query - you can see the query parameters are reflected as it is

https://xyz.com/market-to-cash/em/m?ticker-symbol=c%3A%2F&unique-identifier-type=**unique-identifier-type**&unique-identifier-code=**unique-identifier-code**&rate-source=**rate-source**&page-number=10&to-date=**to-date**&from-date=**from-date**
