### ISSUE TITLE
Automation: job outcome tests

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6496]
Add new 'tests' element to automation jobs.
This should be implemented in the automation add-on in a generic way so that it is available to all jobs without needed to change them.
This functionality will replace the spider 'fail/warnIfFoundUrlsLessThan' parameters - it will have the same effect but be _much_ more flexible.

Suggested yaml:
```
jobs:
  - type: example
    parameters:
      jobSepecficParam: 'blah'
    - tests
      - type: stats                           # Only type initially supported
        statistic: 'stats.addon.something'    # Name of an integer / long statistic
        operator: '>='                        # One of '==', '!=', '>=', '>', '<', '<='
        value: 10                             # Value to conpare against
        action: 'warn'                        # One of 'warn', 'fail', 'ignore'
      - type: stats                           # Only type initially supported
        statistic: 'stats.addon.another'      # Name of an integer / long statistic
        operator: '>='                        # One of '==', '>=', '>', '<', '<='
        value: 10000                          # Value to conpare against
        action: 'fail'                        # One of 'warn', 'fail', 'ignore'
```
The 'ignore' action is so that we can document the stats we would expect people to use without having to actually having to pick any values which would have an effect, and could also be used to 'comment out' tests in a live environment.
Feedback appreciated of course :)
