### ISSUE TITLE
[BUG/missing doc ?] Failed to read https://xxx.xxx.xxx/ within 20 seconds

### ISSUE THREAD

**Issue by flapili** [zaproxy/zaproxy#6693]
**Describe the bug**
can't use zaproxy docker installation behind a reverse proxy (nginx)

**To Reproduce**
install docker & docker-compose

docker-compose.yml
```
version: "3.6"

services:
    owasp:
        restart: unless-stopped
        user: zap
        ports:
          - "8080:8080"
        image: owasp/zap2docker-stable
        command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=${API_KEY}
```
docker-compose up -d

nginx configuration
```nginx
map $http_upgrade $connection_upgrade {
default upgrade;
'' close;
}

server {
    listen 443 ssl http2;
    listen [::]:433 ssl http2;
    server_name xxx.xxx.xxx;

    location / {
        add_header Strict-Transport-Security "max-age=31536000" always;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass https://localhost:8080;
        include /etc/nginx/proxy_params;
    }
    ssl_certificate /etc/letsencrypt/live/xxx.xxx.xxx/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/xxx.xxx.xxx/privkey.pem; # managed by Certbot
}
```

**Expected behavior**
acces to zaproxy behind reverse proxy
**Software versions**
 - ZAP:  owasp/zap2docker-stable (7b07a02e2403)

** actual result**
```
Failed to read https://xxx.xxx.xxx/ within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
```

**Comment by thc202** [comment]
ZAP does not know that the address is itself, you should proxy through that address and use the `zap` domain. (Or rewrite the requests to match what the host/port ZAP was set to listen to.)

Closing as duplicate of #3796.

**Comment by flapili** [comment]
I'm not sure to understand you @thc202 , I also tried to bind directly docker to all interfaces and bypass nginx, but same issue:

```
version: "3.6"

services:
    owasp:
        restart: unless-stopped
        user: zap
        ports:
          - "0.0.0.0:8080:8080"
        image: owasp/zap2docker-stable
        command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=${API_KEY}
```

```
curl https://xx.xx.xx.xx:8080 --insecure
Failed to read https://xx.xx.xx.xx:8080/ within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.root
```
What should I do ?
I don't understand how should I use the zap domain with docker

Best regard
