### ISSUE TITLE
Automation Framework ActiveScanJob: Add ScannerParams to scanRun

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#7012]
**Is your feature request related to a problem? Please describe.**
1. The already defined ScannerParams in the ActiveScanJob are not used. (as far as I can see)
Only ScanPolicy is added to contextSpecificObjects [here](https://github.com/zaproxy/zap-extensions/blob/b48ff78b20d57833015082ed2dccbdb58c3ad57b/addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ActiveScanJob.java#L217). And defined properties like `MaxScanDurationInMins` are not used
2. Furthermore we should add the ScannerParams `targetParamsInjectable` and `targetParamsEnabledRPC`  ([see here](https://github.com/zaproxy/zaproxy/blob/fb2088a0c2285b766b7283752014ba491a50a1bc/zap/src/main/java/org/parosproxy/paros/core/scanner/ScannerParam.java#L171)) to the ActiveScanJob Parameters.
UI View of these parameters:
![image](https://user-images.githubusercontent.com/3629463/148643856-62a1bfb9-65d7-4c35-8678-3975ac2bfe92.png)
We should make it simple to set these bitflag properties (simple as in the UI). Therefore we should introduce boolean parameters in the ActiveScanJob for each BitFlag. As proposal we can define following further boolean properties in the ActiveScanJob:
```
- parameters:
    injectableTarget:
        urlQueryStringAndDataDrivenNodes: true
        addUrlQueryParam: false
        postData: true
        urlPath: true
        httpHeaders: true
        httpHeadersAllRequests: false
        CookieData: true
    inputVectorHandler:
        multiPartFormData: true
        xml: true
        json: true
        jsonScanNullValues: true
        googleWebToolkit: true
        OData: true
        DirectWebRemoting: true
  name: "activeScan"
  type: "activeScan"
```

**Comment by psiinon** [comment]
I would move them one level higher up and make them plural, eg
```
- type: activeScan 
  parameters:
    # As now
  policyDefinition:
    # As now
  injectableTargets:
  inputVectorHandlers:
```
The `parameters` section is really used for `key: value` settings rather than structured data which is why `policyDefinition` is one level higher too.

Its also worth noting that setting `postData` to false will disable most of the inputVectorHandlers. 
Do we want to reflect this in the structure? 
Note that we dont reflect that in the desktop options, or even disable the relevant checkboxes, but this is an opourtunity to make thinks better if we can ;)
Thoughts @thc202 @kingthorin
