### ISSUE TITLE
Automation Framework: Extend ScriptJob

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#7025]
- [x] Add a script (and enable it)
- [x] Run a script that does not exist yet. `action: run` supports a path param so that the script doesnt have to be pre configured in ZAP. If supplied then the script would be registered by ZAP when the action runs.
- [ ] Run a targeted script (Inital mentioned [here](https://github.com/zaproxy/zap-extensions/pull/3433#discussion_r783811790))
```
  parameters:
    action: run
    type: targetted
    name: 'My action'
  scriptParameters:
    target: http://www.example.com/
```
- [x] Remove a script
- [ ] Enable a script
- [ ] Disable a script

yaml schema:
```
- type: script
  parameters:
    action:	
    type:
    name:	        
    file:
    engine:
```
