### ISSUE TITLE
OpenAPI can't handle multiple content types from OAS3 specification

### ISSUE THREAD

**Issue by majstorki88** [zaproxy/zaproxy#7082]
**Describe the bug**
We are having endpoint that can handle multiple content types, and here is the specification:

```yaml
openapi: 3.0.3
info:
  title: Example specification
  version: v1
paths:
  /multiple:
    post:
      summary: Example multiple
      description: >
        multiple content types reques.
      operationId: Multiple_Content_Type
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - files
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
          application/json:
            schema:
              required:
              - fileLinks
              properties:
                fileLinks:
                  type: array
                  items:
                    type: string
                    format: uri
      responses:
        200:
          description: OK
```
**To Reproduce**
1. Run zap from zap weekly image: 

```cmd
docker run --rm -e ZAP_AUTH_HEADER_VALUE="Bearer $TOKEN" -v "%cd%":/zap/wrk -it --user root owasp/zap2docker-weekly zap.sh -cmd -config rules.domxss.browserid=chrome-headless -autorun /zap/wrk/config.yaml
```
`config.yaml` is as follows:

```yaml
env:
  contexts:
  - name: "context 1"
    urls:
    - "http://localhost"
    authentication:
      method: "manual"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
- parameters:
    updateAddOns: false
  name: "addOns"
  type: "addOns"
- parameters:
    apiFile: "wrk/example.yaml"
    targetUrl: "http://localhost"
  name: "openapi"
  type: "openapi"
- parameters:
    maxDuration: 5
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: ""
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
  name: "activeScan"
  type: "activeScan"
```

**Expected behavior**
Expect to run open API tests with multiple content types.

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
```cmd
Found Java version 11.0.13
Available memory: 25462 MB
Using JVM args: -Xmx6365m
2397 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /root/.ZAP_D/config.xml
3011 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP_D/session
3012 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP_D/dirbuster
3012 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP_D/fuzzers
3013 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP_D/plugin
Feb 10, 2022 2:02:34 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Job authentication set method = manual
Job addOns set updateAddOns = false
Job openapi set apiFile = wrk/example.yaml
Job openapi set targetUrl = http://localhost
Job passiveScan-wait set maxDuration = 5
Job activeScan set context =
Job activeScan set user =
Job activeScan set policy =
Job activeScan set maxRuleDurationInMins = 0
Job activeScan set maxScanDurationInMins = 0
Job activeScan set defaultStrength = medium
Job activeScan set defaultThreshold = medium
Job addOns started
Job addOns finished
Unrecognised parameter for job openapi : apiFile
Unrecognised parameter for job openapi : targetUrl
Job openapi started
Job openapi target: http://localhost error: Failed to parse OpenAPI definition.

java.lang.StringIndexOutOfBoundsException: begin 2, end 38, length 26
Job openapi added 0 URLs
Job openapi finished
Automation plan failures:
        Job openapi target: http://localhost error: Failed to parse OpenAPI definition.

java.lang.StringIndexOutOfBoundsException: begin 2, end 38, length 26
Automation plan warnings:
        Unrecognised parameter for job openapi : apiFile
        Unrecognised parameter for job openapi : targetUrl
```
