### ISSUE TITLE
Automation Framework: Technology Support

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7127]
Extend the Automation Framework to support the technology flags for a context.
First step is to propose an extension to the environment yaml: https://www.zaproxy.org/docs/desktop/addons/automation-framework/environment/
The implementation should include the UI changes as well as full unit tests.

**Comment by njmulsqb** [comment]
Ok so commenting on the first step, how about the following structure to include in the YAML file? I have replicated this from the Technology tab from GUI
```
technology:
  DB:
	- CouchDB
	- Firebird
	- MySQL
	- rest of the DBs
  Language:
	- ASP
	- C
	- JSP
	- ... 
  OS:
	- Linux
	- Windows
	- MacOS
  SCM:
	- Git
	- SVN
  WS:
	- Apache
	- IIS
	- Tomcat
```
