### ISSUE TITLE
make variable substitution work anywhere in yaml

### ISSUE THREAD

**Issue by rethab** [zaproxy/zaproxy#7201]
### Is your feature request related to a problem? Please describe.

I have tried to use (env) variables in my YAML file for the automation framework, but it looks like variables only work in the `env.ctx` section of that YAML.

### Describe the solution you'd like

It would be nice if I could write a YAML file like so:

```yaml
env:
  contexts:
    # .. my context
jobs:
  - type: "openapi"
     parameters:
       apiFile: ${OPENAPI_FILE}
```

Additionally, using variables defined in `env.vars` should be usable across the configuration as well:

```yaml
```yaml
env:
  contexts:
    # .. my context
  vars:
    myApiFile: openapi.json
jobs:
  - type: "openapi"
     parameters:
       apiFile: ${myApiFile}
```

### Describe alternatives you've considered

I have also tried pulling in the environment variables via `env.parameters.vars`, like so:

```yaml
env:
  contexts:
    # .. my context
  vars:
    openapiFile: ${OPENAPI_FILE}
jobs:
  - type: "openapi"
     parameters:
       apiFile: ${openapiFile}
```

### Additional context

- When I use a variable that does not exist somewhere in the `env.contexts`, I get an error saying "Variable myVariable used but not specified", but when I try `${myVariable}` in the `jobs` section, it's just `null`
- I looked at the PR that implemented variable substitution for the automation framework (https://github.com/zaproxy/zap-extensions/pull/2883) and it looks pretty clear to me that this only works for the `env` section.
- However that PR also contains some docs, like this line: `vars: # List of 1 or more variables, can be used throughout the config`. This seems to suggest that variables can be used throughout the config.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Also none of the integers support substitution (from memory).
This was reported via IRC.

**Comment by rethab** [comment]
Thanks for your comments @thc202 and @psiinon . As I said in the description, I'd be happy to take a shot at fixing this. Is that ok? If so, is there anything I should consider or shall I just go ahead and see if I can get it to work?

**Comment by psiinon** [comment]
@rethab great! I'm assigned this issue to you.
We do have a load of docs eg https://www.zaproxy.org/docs/contribute/coding/
I've labelled this as a 'good first issue' as there are already examples in the code of how to do this, but if you need any pointers then just say.
We do need unit tests for all PRs but again, if you need any advice and guidance for that then just say.
You dont have to fix everything in your first PR - just fixing one instance would be fine and a good way to get used to our proceedures :)

**Comment by rethab** [comment]
I have created a PR which should support substitution anywhere in `jobs: `: https://github.com/zaproxy/zap-extensions/pull/3724

I have not looked at integer substitution though. Could you please give an example of something that doesn't work @psiinon ?

**Comment by psiinon** [comment]
Many thanks!
I did a quick grep for `Integer.parseInt` and `Long.parseLong` - the main uses that worry me are in JobUtils.objectToType( ..) but if the substitutions have always been applied at that point then we should be ok...

**Comment by rethab** [comment]
Thanks @psiinon . Reading @thc202 comment in the PR about applying the substitutions only right before running the job (which I think makes sense), I'll have to think about this again :)

**Comment by twolfart** [comment]
> I have not looked at integer substitution though. Could you please give an example of something that doesn't work @psiinon ?

```
env:
  vars:
    SPIDER_DURATION: 5

jobs:
  - type: spider
    parameters:
      maxDuration: ${SPIDER_DURATION}
```

Results in:
```
Automation plan failures:
        Invalid value for job spider parameter maxDuration - ${SPIDER_DURATION} should be an integer
```

**Comment by magmax** [comment]
Same problem happens in other points:
```
env:
  vars:
    OUTPUT_PATH: /tmp/zap
    ENVIRONMENT: whatever
- parameters:                                                        
    template: "sarif-json"                                           
    reportDir: "${OUTPUT_PATH}"
    reportFile: "sharif"                                             
    reportTitle: "ZAP Scan for ${ENVIRONMENT}"                                          
  name: "report"                                                     
  type: "report"                                                     
```

won't create the directory `/tmp/zap`, but would try to use `${OUTPUT_PATH}`, what probably doesn't exist and will fail. Fixing it, it will create the report with the wrong title again.

Not creating a different ticket because the title of this one matches my problem as well.

**Comment by javanegmond** [comment]
I would like to bring this one to attention again. There are probably a variety of points where variable substitution isn't applied as of yet. One of them I noticed is `env.contexts[*].authentication.verification.pollUrl`, which is inline with what I would expect based on the comments in the (unfortunately closed) PR https://github.com/zaproxy/zap-extensions/pull/3724.

One main problem that seems to be open is how to deal with variables in the env-part; since that is also where the `vars` definition lives. The short of it to me is that it kinda seems that anything but the vars might not actually fit properly in `env`. Personally I have no time to contribute on this with code, but I see a couple of possible ways forward.

For dealing with System environment variables, here's a number of thoughts:
1. Only allow system environment variable substitution within the `env` part.
2. Detect used system environment vars once (any variable to be expanded that does not appear in `env.vars` could/should be treated as a system env var?) and add them _transciently_ to `env.vars` only while processing the plan as new `key: <rendered system env value>` pairs.

For performing actual variable substitutions, I would look at these options:
1. Perform variable substitutions in a recursive or looping manner over the whole plan, with the stop condition being either a stable state (to allow for variables referencing other variables), a formerly seen state (to block simple circular variable references) or a maximum number of steps (to block more complex circular variable references without additional logic.
2. The above, but build a variable reference graph to detect cyclic references as a precondition.

Additionally, perhaps a restructuring of the jobs could greatly improve how plans look. Remove anything but the `vars` from the `env` job and put them into their own jobs. This would probably still need to implement either of the above options to deal with variable references in the `env.vars` part. Personally I'm a fan of this because currently it seems the `env` job has too many responsibilities. It'll likely be hard to make backwards compatible though, so I can understand not moving forward on this immediately.

**Comment by psiinon** [comment]
If we did that then if you are editing the plan in ZAP then you would loose all of the variables when you save the plan.
We need the variables to stay in place in order for us to be able to edit the plan correctly in ZAP.
Also, some of the variables might not have the correct values until runtime.

**Comment by psiinon** [comment]
Apparently the session script fails `script: "${pathPrefix}/scripts/session/session.js"`

**Comment by maxkrumpe** [comment]
> Apparently the session script fails `script: "${pathPrefix}/scripts/session/session.js"`

To complete this sentence:

I define a variable called "prefixPath" in env.vars and want to reuse it in the script parameters to not repeat myself again and again.

The current automation.yml looks like this:
```
env:
  contexts:
  - name: Authentication Context
    urls:
    - https://mydomain.de/
    includePaths:
    - https://mydomain.de/.*
    authentication:
      method: script
      parameters:
        script: "${pathPrefix}/scripts/authentication/authenticate.js"
        scriptEngine: Graal.js
      verification:
        method: poll
        loggedInRegex: \Q200\E
        loggedOutRegex: \Q401\E
        pollFrequency: 60
        pollUnits: requests
        pollUrl: https://mydomain/v1/user/data
        pollPostData: ""
        pollAdditionalHeaders:
        - header: content-type
          value: application/json
    sessionManagement:
      method: script
      parameters:
        script: "${pathPrefix}/scripts/session/session.js"
        scriptEngine: Graal.js
    technology: {}
    structure: {}
    users:
    - name: produser
      credentials:
        password: "${AUTH_PSW}"
        username: "${AUTH_USR}"
  parameters: {}
  vars:
    pathPrefix: "/zap/wrk"
```
