### ISSUE TITLE
URL's get concatenated when reading automation yaml script

### ISSUE THREAD

**Issue by rafaelszp** [zaproxy/zaproxy#7241]
### Describe the bug

When there are multiple URL's in contexts configured per context in automation file (yaml), all URL's get concatenated in ZAP UI box causing scan tests not to work properly because URL's are concatenated

### Steps to reproduce the behavior

1. Make an automation file (yaml). 
2. Put mulple URL's inside any context
3. Load yaml file in ZAP UI through automation tab
4. Open env/contexts/yourcontext and navigate to the first tab. Note all URL's are concatenated

### Expected behavior

We expect all URL's to be separated by line. like includes/excludes text box.

### Software versions

ZAP 2.11.1

### Screenshots

![image](https://user-images.githubusercontent.com/1713351/165109361-2798ad56-3531-49e8-9552-aaa118cd53cc.png)
![image](https://user-images.githubusercontent.com/1713351/165109506-560d15d6-6a03-4103-93eb-30d48ae960d3.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Could you share the files or a screenshot?

**Comment by kingthorin** [comment]
Could you please provide full version information, so that we know which Automation add-on you have etc.

>  Please add version information from ZAPs menu Help > Support Info, or from the CLI using the -suppinfo switch

**Comment by rafaelszp** [comment]
Automation yaml file:

```yaml
---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "https://httpbin.org"
    - "https://google.com"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters: {}
  name: "script"
  type: "script"
```

ZAP Support Info:

```OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=46.0.0], [id=ascanrulesAlpha,
version=38.0.0], [id=ascanrulesBeta, version=40.0.0],
[id=automation, version=0.15.0], [id=bruteforce,
version=11.0.0], [id=commonlib, version=1.9.0],
[id=communityScripts, version=14.0.0], [id=custompayloads,
version=0.11.0], [id=diff, version=11.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=12.0.0], [id=encoder, version=0.6.0], [id=exim,
version=0.1.0], [id=formhandler, version=4.0.0], [id=fuzz,
version=13.6.0], [id=fuzzdb, version=8.0.0],
[id=fuzzdboffensive, version=4.0.0], [id=gettingStarted,
version=13.0.0], [id=graaljs, version=0.2.0], [id=help,
version=14.0.0], [id=invoke, version=11.0.0], [id=jsonview,
version=2.0.0], [id=jwt, version=1.0.2], [id=jython,
version=12.0.0], [id=network, version=0.2.0], [id=oast,
version=0.10.0], [id=onlineMenu, version=9.0.0],
[id=openapi, version=27.0.0], [id=pscanrules,
version=40.0.0], [id=pscanrulesAlpha, version=35.0.0],
[id=pscanrulesBeta, version=29.0.0], [id=replacer,
version=9.0.0], [id=reports, version=0.13.0], [id=requester,
version=5.0.0], [id=retest, version=0.2.0], [id=retire,
version=0.10.0], [id=reveal, version=4.0.0], [id=scripts,
version=30.0.0], [id=selenium, version=15.8.0],
[id=spiderAjax, version=23.7.0], [id=sqliplugin,
version=15.0.0], [id=tips, version=9.0.0], [id=treetools,
version=8.0.0], [id=viewstate, version=3.0.0],
[id=webdriverlinux, version=37.0.0], [id=zest,
version=35.0.0]]
---
Operating System: Linux
Java Version: Azul Systems, Inc. 1.8.0_282
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
ZAP Home Directory: /home/rafael/.ZAP/
ZAP Installation Directory: /home/rafael/dev/tools/ZAP_2.11.1/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```
