### ISSUE TITLE
Duplicated script output when running an Automation Plan in command line mode

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7455]
### Describe the bug

The script print statements are printed twice to the standard output.

### Steps to reproduce the behavior

1. Run the provided automation plan in command line mode (adjusting file system paths as needed), e.g.:
   `./zap.sh -cmd -autorun /path/to/run-script.yaml`
2. Check the output and notice the duplicated script output (`Script print statement.`), .e.g:
```
Job Add Script set action = add
Job Add Script set type = standalone
Job Add Script set engine = ECMAScript : Oracle Nashorn
Job Add Script set name = PrintStatement
Job Add Script set file = /path/to/print.js
Job Run Script set action = run
Job Run Script set type = standalone
Job Run Script set name = PrintStatement
Job script started
Job: Add Script Start action: add
Job script finished
Job script started
Job: Run Script Start action: run
Script print statement.
Script print statement.
Job script finished
Automation plan succeeded!
```

Automation Plan `run-script.yaml`
```yaml
---
env:
  contexts:
  - name: "test"
    urls:
    - "example.com"
    includePaths:
    excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    action: "add"
    type: "standalone"
    engine: "ECMAScript : Oracle Nashorn"
    name: "PrintStatement"
    file: "/path/to/print.js"
  name: "Add Script"
  type: "script"
- parameters:
    action: "run"
    type: "standalone"
    name: "PrintStatement"
  name: "Run Script"
  type: "script"
```

Script `print.js`
```js
print("Script print statement.");
```

### Expected behavior

Print statements are printed just once.

### Software versions

Automation Framework version 0.17.0.
ZAP version 2.11.x.
Also happening when built from source.

### Additional context

From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/8u9ePH0Mjlo/m/hhFk6WQwBgAJ

**Comment by njmulsqb** [comment]
Hi, can't reproduce this as it says `Unrecognised job type: script`. Here's the YAML I am using
```
---
env:
  contexts:
  - name: "test"
    urls:
    - "example.com"
    includePaths:
    excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    action: "add"
    type: "standalone"
    engine: "ECMAScript : Oracle Nashorn"
    name: "PrintStatement"
    file: "C:\\Users\\Ain\\Desktop\\print.js"
  name: "Add Script"
  type: "script"
- parameters:
    action: "run"
    type: "standalone"
    name: "PrintStatement"
  name: "Run Script"
  type: "script"
```
Output:
```
> Task :zap:ZAP.main()
Unrecognised job type: script
Unrecognised job type: script
Automation plan failures:
	Unrecognised job type: script
	Unrecognised job type: script
```
