### ISSUE TITLE
Latest owasp/zap2docker-stable can't find Java 11

### ISSUE THREAD

**Issue by r8ygun** [zaproxy/zaproxy#7556]
### Describe the bug

Using the image `owasp/zap2docker-stable` and running `zap-api-scan.py` results in the following error:

```
Exiting: ZAP requires a minimum of Java 11 to run, found 
```

### Steps to reproduce the behavior

The full command that we run is:

```
zap-api-scan.py -I -d -r owasp_report.html -J owasp_report.json -t ${openapi_target} -f openapi -O ${docker_service}:${docker_port} -c api-scan-config.conf
```

### Expected behavior

We would expect the ZAP container to start correctly, but it doesn't and times out after a while.

### Software versions

owasp/zap2docker-stable:latest

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
What imageid?

**Comment by r8ygun** [comment]
@kingthorin 7a669aec036cb47107463c10a722fb581da3e7200b816de3feb92f05ccbcdb03

**Comment by kingthorin** [comment]
Is it customized? Because your command shows you writing and expecting files within the docker container

**Comment by r8ygun** [comment]
@kingthorin The image isn't customised, we use that command in docker-compose and mount a volume from the host where the expected/output files are.

**Comment by kingthorin** [comment]
So you're running docker in docker?

**Comment by psiinon** [comment]
I've just tried `docker run -t owasp/zap2docker-stable zap-api-scan.py -t https://petstore.swagger.io/v2/swagger.json -f openapi -d` and it starts ZAP correctly, so this looks like its a problem with the way you are running it.

**Comment by knguye303** [comment]
I'm getting the same issue running on circleci executors `docker run -it   --name=zap-proxy   --network=zap-network   -p 8081:8081   -i owasp/zap2docker-stable   zap-x.sh -daemon -host 0.0.0.0   -port 8081   -config api.addrs.addr.name=.*   -config api.addrs.addr.regex=true   -config api.key="${LOCAL_API_KEY}"`. Running on `java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)`

**Comment by psiinon** [comment]
It works when run the way we document.
What happens if you try to run java instead of a script?
Can anyone provide a simple way we can reproduce this problem?

**Comment by r8ygun** [comment]
My apologies for the lack of response on this and missing context.

We make use of ZAP by running it in Docker with `docker-compose`. Our repositories have an existing docker-compose.yml file that is used to spin up their application, and for testing with ZAP we essentially inject ZAP into this docker-compose file like so:

```
version: $version
services:
  owasp_zap:
    image: owasp/zap2docker-stable
    depends_on:
      - ${docker_service}
    command: zap-api-scan.py -I -d -r owasp_report.html -J owasp_report.json -t ${openapi_target} -f openapi -O ${docker_service}:${docker_port} -c api-scan-config.conf
    container_name: ${owasp_zap_container_name}
    volumes:
      - ./owasp-zap:/zap/wrk
```

`${docker_service}`, `${docker_port}` are the services we're testing, which have an OpenAPI endpoint, the path to which is stored in `${openapi_target}`.

We have run this script on GoCD agents (which are just EC2 instances) and on our GitLab runners (in k8s) - both fail. We have examples of pipelines passing as recently as 2022-10-27 with the script unchanged. This failure seems to have started in the last day as changing from `latest` to an older tag works.

We can't reproduce this running locally with `docker run owasp/zap2docker-stable:latest zap-api-scan.py...` (this works fine).
