### ISSUE TITLE
Addon automation maxRuleDurationInMins

### ISSUE THREAD

**Issue by ErvisTusha** [zaproxy/zaproxy#7638]
### Describe the bug

Hello!
Hope you are ok 
I have set maxRuleDurationInMins 1 minute but it doesn't skip to next rule 
Maybe its a Active Scan ( GUI ) bug because when I try to skip to next rules doesn't skip 

### Steps to reproduce the behavior

`zaproxy -cmd -nostdout -silent -autorun /root/ET/examples/zap.yaml`

```
---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "https://ginandjuice.shop"
    includePaths:
    - "https://ginandjuice.shop.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: ""
    user: ""
    url: ""
    maxDuration: 1
    maxDepth: 0
    maxChildren: 0
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 1
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: ""
    user: ""
    policy: ""
    maxRuleDurationInMins: 1
    maxScanDurationInMins: 10
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "risk-confidence-html"
    reportDir: "/home/kali"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
```

### Expected behavior

Skip to next Rule 

### Software versions

Zaproxy 2.12.0
Automation 0.19.0
OS Kali 

### Would you like to help fix this issue?

- [ ] Yes
