### ISSUE TITLE
Addon automation error scanning when is website with ports 

### ISSUE THREAD

**Issue by ErvisTusha** [zaproxy/zaproxy#7649]
### Describe the bug

zaproxy fail to scan when target is set with port for example http://testphp.vulnweb.com:80

zaproxy -cmd -autorun /root/ET/vulnweb.com_80.yaml

```yml
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://testphp.vulnweb.com:80"
    includePaths:
    - "http://testphp.vulnweb.com:80.*"
    excludePaths: []
    authentication:
```

### Steps to reproduce the behavior

zaproxy -cmd -autorun /root/ET/vulnweb.com_80.yaml

### Expected behavior

scan as normal 

### Software versions

zaproxy 2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please elaborate on "fail"

**Comment by ErvisTusha** [comment]
```
Found Java version 17.0.5
Available memory: 128731 MB
Using JVM args: -Xmx32182m
340 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /root/.ZAP/config.xml
451 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP/session
451 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP/dirbuster
452 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP/fuzzers
452 [main] INFO  org.parosproxy.paros.Constant - Creating directory /root/.ZAP/plugin
Dec 20, 2022 11:08:04 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Job authentication set parameters = {}
Job verification set method = response
Job verification set pollFrequency = 60
Job verification set pollUnits = requests
Job sessionManagement set method = cookie
Job sessionManagement set parameters = {}
Unrecognised parameter for job Automation Context : technology
Job passiveScan-config set scanOnlyInScope = true
Job passiveScan-config set enableTags = false
Job spider/stats set onFail = Info
Job spider/stats set statistic = automation.spider.urls.added
Job spider/stats set site = 
Job spider/stats set operator = >=
Job spider/stats set value = 100
Job spider/stats set name = At least 100 URLs found
Job spider/stats set type = stats
Job spider adding test of type stats : At least 100 URLs found
Job spiderAjax set maxDuration = 60
Job spiderAjax set maxCrawlDepth = 10
Job spiderAjax set numberOfBrowsers = 1
Job spiderAjax/stats set onFail = Info
Job spiderAjax/stats set statistic = spiderAjax.urls.added
Job spiderAjax/stats set site = 
Job spiderAjax/stats set operator = >=
Job spiderAjax/stats set value = 100
Job spiderAjax/stats set name = At least 100 URLs found
Job spiderAjax/stats set type = stats
Job spiderAjax adding test of type stats : At least 100 URLs found
Job report set template = risk-confidence-html
Job report set reportDir = /home/ET
Job report set reportTitle = ZAP Scanning Report
Job report set reportDescription = 
Job passiveScan-config started
Job passiveScan-config finished
Job spider started
Job spider requesting URL http://testphp.vulnweb.com:80
Job spider found 0 URLs
Job spider test of type stats failed: At least 100 URLs found [0 < 100]
Job spider finished
Job spiderAjax started
Job spiderAjax found 0 URLs
Job spiderAjax test of type stats failed: At least 100 URLs found [0 < 100]
Job spiderAjax finished
Job passiveScan-wait started
Job passiveScan-wait finished
Job activeScan started
Job activeScan finished
Job report started
Job report generated report /home/ET/2022-12-20-ZAP-Report-testphp.vulnweb.com.html
Job report finished
Automation plan warnings:
        Unrecognised parameter for job Automation Context : technology
```

**Comment by kingthorin** [comment]
"warnings" ?

**Comment by kingthorin** [comment]
```
Job spider requesting URL http://testphp.vulnweb.com:80
Job spider found 0 URLs
Job spider test of type stats failed: At least 100 URLs found [0 < 100]
Job spider finished
Job spiderAjax started
Job spiderAjax found 0 URLs
Job spiderAjax test of type stats failed: At least 100 URLs found [0 < 100]
```

That part?

**Comment by kingthorin** [comment]
Also, could you provide your full plan as requested earlier.

**Comment by ErvisTusha** [comment]
Sorry I'm writing from my phone
I'm using default Full Scan only change is add port 80

**Comment by kingthorin** [comment]
The issue seems to be that you're specifying a default port (http = 80, https = 443). It doesn't match anything in your site tree, so essentially nothing is found/scanned. If you were specifying a non-standard port that does serve content it works as expected.

**Comment by kingthorin** [comment]
<details>
<summary>Plan I tested with</summary>

```yml
---
env:
  contexts:
  - name: "Default Context"
    urls:
        - "http://testphp.vulnweb.com:80"
    includePaths:
    - "http://testphp.vulnweb.com:80.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"

```

</details>

My eclipse run config arguments: `-autorun C:\Users\thorin\Desktop\test\test2.yaml`

**Comment by kingthorin** [comment]
<details>
<summary>Secondary plan I tested with</summary>

```yml
---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://localhost:81"
    includePaths:
    - "http://localhost:81.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
```

</details>

Same run config. localhost:81 was an Apache server via XAMPP. It worked as expected.

```console
   Job passiveScan-config started
   Job passiveScan-config finished
   Job spider started
   Job spider requesting URL http://localhost:81
   Job spider found 3,054 URLs
   Job spider test of type stats passed: At least 100 URLs found [3054 >= 100]
   Job spider finished
   Job passiveScan-wait started
   Job passiveScan-wait finished
```
