### ISSUE TITLE
Traditional JSON report includes out-of-scope sites

### ISSUE THREAD

**Issue by trigger1919** [zaproxy/zaproxy#7656]
### Describe the bug

Starting from ZAP 2.12.0 the report generated either by UI or AF produces the out-of-scope sites.

AF config file is defined with the context:

```
env:
  contexts:
  - name: "context_test"
    urls:
    - "${TARGET_BASE_URL}/"
    includePaths:
    - "${TARGET_BASE_URL}.*"
    excludePaths:
    - "\\\\Q${TARGET_BASE_URL}/logout\\\\E([/?#]|$)"
    - "${TARGET_BASE_URL}/auth/logout"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
```

The output json generated by the job:
```
parameters:
    template: "traditional-json"
    reportDir: "wrk"
    reportFile: "report"
    reportTitle: "zap-report"
    reportDescription: ""
    displayReport: false
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  name: "report"
  type: "report"
```

produces JSON file with unexpected sites in it (I changed the real site names to site1, 2, 3):

```
{
	"@programName": "OWASP ZAP",
	"@version": "2.12.0",
	"@generated": "Thu, 15 Dec 2022 14:07:48",
	"site":[ 
		{
			"@name": "https://site1",
			"@host": "site1.com",
			"@port": "443",
			"@ssl": "true",
			"alerts": [ 
			]
		},
		{
			"@name": "https://site2",
			"@host": "site2",
			"@port": "443",
			"@ssl": "true",
			"alerts": [ 
			]
		},
		{
			"@name": "https://site3",
			"@host": "site3",
			"@port": "443",
			"@ssl": "true",
			"alerts": [ 
			]
		},
```
along with the in-scope site.

### Steps to reproduce the behavior

See steps in the description

### Expected behavior

Only in-scope sites are included in the report.

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes
