### ISSUE TITLE
alertFilter job is broken for Automation Framework

### ISSUE THREAD

**Issue by UgniusV** [zaproxy/zaproxy#7833]
#### Summary
The `alertFilter` job seems to have no effect when used in Automation Framework. No re-writing is being done. 

#### Steps to reproduce
Run Automation Framework scan and pick a vulnerability that you would like to rewrite risk for. In my case, I picked `90022` (Application Error Disclosure) and `10202` (Missing CSRF tokens). Both of these vulnerabilities are considered to be of medium risk by default.
```yaml
  - parameters: {} # Alert filter can be used to rewrite risks of certain findings
    name: "alertFilter"
    type: "alertFilter"
    alertFilters: # https://groups.google.com/g/zaproxy-users/c/3EH7yB__eG0 Still a bug
      - ruleId: 90022 # Application Error Disclosure
        newRisk: "Low"
      - ruleId: 10202 # Missing CSRF tokens
        newRisk: "Low"
  - parameters: # Report job is responsible for generating the final report
      template: "traditional-pdf" # Modern template generates an HTML report, to generate a PDF use traditional-pdf
      reportDir: "/tmp"
      reportFile: "ZAP-Report-[[site]]"
    name: "report"
    type: "report"
```
Once the plan finishes and the report is generated, it is visible that these findings are not rewritten and still are classified as "medium" risks

<img width="443" alt="Screenshot 2023-04-20 at 11 52 50" src="https://user-images.githubusercontent.com/18017952/233313473-b3a405e4-2c4c-4fee-a6c6-830866d1bb63.png">

#### References
There is a very similar open ticket [here](https://groups.google.com/g/zaproxy-users/c/3EH7yB__eG0)
