### ISSUE TITLE
Report AF job - add support for sites

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7858]
The report add-on allows you to limit the alerts included to a set of sites that you specify via the ZAP desktop.
That is not currently possible in the Automation Framework [reports](https://www.zaproxy.org/docs/desktop/addons/report-generation/automation/) job.
This issue is to enhance the reports job so that the user can optionall specify a set of sites, eg:
```
- type: report
    parameters:
      reportTitle: "My report"
    risks: 
      - high
    sites: 
      - https://www.example.com/
      - https://api.example.com/
```
