### ISSUE TITLE
AF: traditional-pdf report template generates a "cut-off" PDF report

### ISSUE THREAD

**Issue by UgniusV** [zaproxy/zaproxy#7885]
### Describe the bug

When using `traditional-pdf` report template with Automation Framework, the generated PDF has sections that are "cut-off". One such example is the description section. Please see the screenshot below:
<img width="958" alt="Screenshot 2023-05-31 at 13 51 26" src="https://github.com/zaproxy/zaproxy/assets/18017952/af7b172f-146f-4ce0-b907-3d8371854d4c">

The description is not formatted correctly, and half of it is not visible, resulting in "hard-to-read" reports.

### Steps to reproduce the behavior

When using Automation Framework, try to generate the report with `traditional-pdf` template:
```yaml
  - parameters:
      template: "traditional-pdf"
      reportDir: "/tmp"
      reportFile: "ZAP-Report-[[site]]"
    name: "report"
    type: "report"
```
The resulting report will have sections that are "cut-off", just like in the screenshot above.

### Expected behavior

All sections of the PDF report should be visible and properly formatted.

### Software versions

Tested on latest "fixed version" Docker image: owasp/zap2docker-stable:2.12.0

### Screenshots

<img width="958" alt="Screenshot 2023-05-31 at 13 51 26" src="https://github.com/zaproxy/zaproxy/assets/18017952/3324613c-62e4-4ba3-9a20-478c67d15bf7">

### Would you like to help fix this issue?

- [ ] Yes
