### ISSUE TITLE
Alert Filter automation framework is too granular, doesn't work on alertRef

### ISSUE THREAD

**Issue by locka99** [zaproxy/zaproxy#7922]
### Describe the bug

I want to write an alert filter into an automation framework that specifically filters on alert ref 10055-6 but I can only filter on 10055 which will suppress other alerts that are still legitimate

### Steps to reproduce the behavior

I can do this:

```
- type: alertFilter
  alertFilters:
    -ruleId 10055
      newRisk: "Info
```

But I can't do this:

```
- type: alertFilter
  alertFilters:
    -ruleId 10055-6
      newRisk: "Info
```

### Expected behavior

There should be a new field to filter by an explicit alertRef

### Software versions

2.12.0 Linux

### Would you like to help fix this issue?

- [ ] Yes
