### ISSUE TITLE
Graal.js engine might fail to load/access add-on classes

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7960]
Run the Automation Framework plan:
```yaml
---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "https://example.com"
jobs:
- parameters:
    action: "add"
    type: "standalone"
    engine: "ECMAScript : Graal.js"
    name: "GraalJs"
    inline: "print(Java.type('org.openqa.selenium.By'))"
  type: "script"
- parameters:
    action: "add"
    type: "standalone"
    engine: "ECMAScript : Oracle Nashorn"
    name: "Nashorn"
    inline: "print(Java.type('org.openqa.selenium.By'))"
  type: "script"
- parameters:
    action: "run"
    type: "standalone"
    name: "GraalJs"
  type: "script"
- parameters:
    action: "run"
    type: "standalone"
    name: "Nashorn"
  type: "script"
- parameters:
    action: "run"
    type: "standalone"
    name: "GraalJs"
  type: "script"
```

Check the output:
```
   Job script started
   Job: script Start action: add
   Job script finished, time taken: 00:00:00
   Job script started
   Job: script Start action: add
   Job script finished, time taken: 00:00:00
   Job script started
   Job: script Start action: run
   org.graalvm.polyglot.PolyglotException: TypeError: Access to host class org.openqa.selenium.By is not allowed or does not exist.
   Job script finished, time taken: 00:00:01
   Job script started
   Job: script Start action: run
   [JavaClass org.openqa.selenium.By]
   Job script finished, time taken: 00:00:00
   Job script started
   Job: script Start action: run
   class org.openqa.selenium.By
   Job script finished, time taken: 00:00:00
```

The first time that Graal.js engine was executed it was not able to load the class, while after running Nashorn it was able to access it.

Add-on
GraalVM JavaScript version 0.4.0
