### ISSUE TITLE
Bug Authentication Automation Plan 

### ISSUE THREAD

**Issue by nicollasteixeira** [zaproxy/zaproxy#8035]
### Describe the bug

As talked with Simon at: https://groups.google.com/d/msgid/zaproxy-users/ba7fed3e-70fc-4a19-82bc-a929b72685f6n%40googlegroups.com?utm_medium=email&utm_source=footer

There is a bug in the automation plan for authentication, where it manages to configure the login request but does not use the correct data.

ZAP configured it this way
username={%username%}&password={%username%}

it should be
username={%username%}&password={%password%}

It repeatedly replaces the username variable value instead of applying the username value to the username field and the password variable value to the password field.

### Steps to reproduce the behavior

Following this .yaml automation file
```yaml
---
env:
  contexts:
  - name: "test"
    urls: 
    - "url"
    includePaths: 
    - "url.*"
    excludePaths: []
    authentication:
      method: "autodetect"
      parameters:
        loginPageUrl: "url/login"
        loginPageWait: 20
        browserId: "firefox-headless"
      verification:
        method: "autodetect"
    sessionManagement:
      method: "autodetect"
      parameters: {}
    technology:
      exclude: []
    users:
    - name: "auth"
      credentials:
        username: "administrator"
        password: "password"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 10
    name: "At least 10 URLs found"
    type: "stats"
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 8
    inScopeOnly: true
    excludedElements: []
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters: {}
  policyDefinition:
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "risk-confidence-html"
    reportDir: "dir"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
```

### Expected behavior

It should replace username field with the username variable value and the password field with the password variable value.

### Software versions
```
OWASP ZAP
Version: 2.13.0

Installed Add-ons: [[id=alertFilters, version=17.0.0],
[id=ascanrules, version=56.0.0], [id=attacksurfacedetector,
version=1.1.4], [id=authhelper, version=0.9.0],
[id=automation, version=0.30.0], [id=bruteforce,
version=14.0.0], [id=callhome, version=0.7.0],
[id=commonlib, version=1.16.0], [id=database,
version=0.2.0], [id=diff, version=13.0.0],
[id=directorylistv1, version=6.0.0], [id=domxss,
version=16.0.0], [id=encoder, version=1.2.0], [id=exim,
version=0.6.0], [id=formhandler, version=6.4.0], [id=fuzz,
version=13.10.0], [id=gettingStarted, version=15.0.0],
[id=graaljs, version=0.4.0], [id=graphql, version=0.18.0],
[id=help, version=16.0.0], [id=hud, version=0.17.0],
[id=invoke, version=13.0.0], [id=network, version=0.10.0],
[id=oast, version=0.16.0], [id=onlineMenu, version=11.0.0],
[id=openapi, version=35.0.0], [id=pscanrules,
version=50.0.0], [id=quickstart, version=38.0.0],
[id=replacer, version=13.0.0], [id=reports, version=0.24.0],
[id=requester, version=7.3.0], [id=retest, version=0.6.0],
[id=retire, version=0.25.0], [id=reveal, version=6.0.0],
[id=scripts, version=39.0.0], [id=selenium,
version=15.13.0], [id=soap, version=18.0.0], [id=spider,
version=0.5.0], [id=spiderAjax, version=23.15.0],
[id=sqliplugin, version=15.0.0], [id=tips, version=11.0.0],
[id=webdriverwindows, version=58.0.0], [id=websocket,
version=29.0.0], [id=zest, version=39.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Oracle Corporation 11.0.19
System's Locale: pt_BR
Display Locale: en_GB
Format Locale: pt_BR
Default Charset: windows-1252
ZAP Home Directory: C:\Users\NicollasTeixeira\OWASP ZAP\
ZAP Installation Directory: C:\Program Files\OWASP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```

### Screenshots

![3432d](https://github.com/zaproxy/zaproxy/assets/115294090/96de74a4-fbfa-4e83-9405-d715f4d6d127)

### Would you like to help fix this issue?

- [ ] Yes
