### ISSUE TITLE
Passivescan is run when no passiveScan-Config job is added for the automation framework

### ISSUE THREAD

**Issue by jeremychoi** [zaproxy/zaproxy#8085]
### Describe the bug

(while I'm not sure whether it matters or not, anyway reporting this as it could not be intuitional)
If no passiveScan-Config job is added for the automation framework, Passivescan is still run. 

Since all the other AF jobs seem to only run when explicitly added, the same might want to go for the passivescan jobs. 

 

### Steps to reproduce the behavior

1. create an AF item
2. add an activescan and report job (without passivescan job)
3. run the AF

### Expected behavior

passivescan should not run.

### Software versions

2.13.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Please provide an example AF plan and ensure you have no alerts in your session to start with.

**Comment by jeremychoi** [comment]
sure thing. here is an example plan. 
I tested with a fresh run, e.g. ( $ zap.sh -autorun af.yaml )

```
env:
  contexts:
  - excludePaths: []
    includePaths: []
    name: Default Context
    sessionManagement:
      method: cookie
      parameters: {}
    urls:
    - http://192.168.50.142:5000/
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
jobs:
- name: openapi
  parameters:
    apiUrl: http://192.168.50.142:5000/docs/openapi.json
    context: Default Context
    targetUrl: http://192.168.50.142:5000
  type: openapi
- name: activeScan
  parameters:
    context: Default Context
    policy: sqli-only
    user: ''
  type: activeScan
- name: report
  parameters:
    displayReport: false
    reportDescription: ''
    reportDir: /zap/results/reports/
    reportFile: zap-report.json
    reportTitle: ZAP Scanning Report
    template: traditional-json-plus
  type: report

```
