### ISSUE TITLE
Expose ZAP API from a kubernetes ingress or route on non container ports

### ISSUE THREAD

**Issue by sastorsl** [zaproxy/zaproxy#8239]
### Describe the bug

Running zaproxy as a daemon in a kubernetes pod you need to run the port with either the default port - `8080` - or another high port.
In the kubernetes world a typical scenario is that you expose the service through port 443 or 80 through an ingress, or openshift route, object, often with an haproxy or similar proxy in front.

zaproxy will not accept connections unless the host header match the defined host and port, and will drop the connection.

Accessing zaproxy directly through the kubernetes `Service` object, with the configured port, works as expected.

There is an option to add an **alias** - but the documentation is not very clear on what config option must be added.

### Steps to reproduce the behavior

1. Run zap in a docker container or in kubernetes on port 8080 (or similar)
2. Proxy requests through a standard port such as 80 or 443
3. Observe connection timeout

### Expected behavior

Either that this port / host header check is disabled, but better is that the relevant configuration options are documented in a central place so it is possible to find which config options must be added.

### Software versions

zaproxy-2.14.0

### Screenshots

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: zaproxy-api-11-t6jbc
  namespace: zaproxy
spec:
  containers:
  - args:
    - -daemon
    - -silent
    - -host
    - 0.0.0.0
    - -port
    - "8080"
    - -Xmx1536m
    - -config
    - api.addrs.addr.name=.*
    - -config
    - api.addrs.addr.regex=true
    - -config
    - api.key=secret-key
    command:
    - zap.sh
    image: ghcr.io/zaproxy/zaproxy:2.14.0
    imagePullPolicy: Always
    name: zaproxy
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    securityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    volumeMounts:
    - mountPath: /zap/wrk
      name: container-emptydir-wrk
  volumes:
  - emptyDir: {}
    name: container-emptydir-wrk
```

### Additional context

Relevant issues and PR's:

* #3594 
* #3796 
* #6693 
* PR #7080 
* PR: zaproxy/zap-extensions#3551

Relevant links:

* https://www.zaproxy.org/docs/api/?shell#networkactionaddalias
* https://www.zaproxy.org/faq/how-do-you-find-out-what-key-to-use-to-set-a-config-value-on-the-command-line/
* https://www.zaproxy.org/docs/desktop/addons/network/options/localservers/#aliases
* https://groups.google.com/g/zaproxy-users/c/ZHq3PwJh6No
* https://groups.google.com/g/zaproxy-users/c/PZ-3sKSz7sw

### Would you like to help fix this issue?

- [ ] Yes

**Comment by sastorsl** [comment]
The solution is to add the relevant alias, which after much digging was found in the linked zaproxy-users forums, issues and PR's.
Documenting the config options would have made this easier.

For reference:

```yaml
spec:
  containers:
  - args:
    - -daemon
    - -silent
    - -host
    - 0.0.0.0
    - -port
    - "8080"
    - -Xmx1536m
    - -config
    - api.addrs.addr.name=.*
    - -config
    - api.addrs.addr.regex=true
    - -config
    - api.key=secret-key
    - -config
    - network.localServers.aliases.alias.name=name-of-ingress-or-route-hostname
    command:
    - zap.sh
```
