### ISSUE TITLE
Zap deployment on kubernetes giving 503

### ISSUE THREAD

**Issue by sam95** [zaproxy/zaproxy#8285]
### Describe the bug

We have deployed zap by creating custom helm templates integrated through argo-cd. Although everything looks healthy and the service is up and running on k8s, it is unable to receive requests from an internal vpc through an ingress. 

service.yaml
```apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: zap
    app.kubernetes.io/name: owasp-zap
    argocd.argoproj.io/instance: zap
  name: zap-owasp-zap
  namespace: zap
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: null
  selector:
    app.kubernetes.io/instance: zap
    app.kubernetes.io/name: owasp-zap
  type: ClusterIP
```
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: zap
    app.kubernetes.io/name: owasp-zap
    argocd.argoproj.io/instance: zap
  name: zap-owasp-zap
  namespace: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zap
      app.kubernetes.io/name: owasp-zap
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zap
        app.kubernetes.io/name: owasp-zap
    spec:
      containers:
        - command:
            - sh
            - '-c'
            - >-
              /bin/bash /zap/zap.sh -daemon -port 8081 -host 0.0.0.0 -config
              api.disablekey=true -config api.addrs.addr.name=.* -config
              api.addrs.addr.regex=true
          image: 'owasp/zap2docker-stable:latest'
          imagePullPolicy: IfNotPresent
          name: owasp-zap
          ports:
            - containerPort: 8080
              name: http
```
deployment.yaml
```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    argocd.argoproj.io/instance: zap
  name: zap-owasp-zap
  namespace: zap
spec:
  ingressClassName: nginx
  rules:
    - host: stage.example.com
      http:
        paths:
          - backend:
              service:
                name: zap-owasp-zap
                port:
                  number: 8081
            path: /zap/?(.*)
            pathType: ImplementationSpecific
```
If we login to the root instance and execute the below curl request, we obtain the expected response. 
Request and response
```
root@jenkins-v1-5946776794-p66mt:/# curl --location --request GET 'http://zap-owasp-zap.zap:8081/JSON/context/view/contextList/' -k  --header 'Accept: application/json'
{"contextList":[]}
```
If we login to the application and execute the below curl request, we obtain the expected response. 
```
zap@zap-owasp-zap-794d7579c6-jp7gp:/zap$ curl --location --request GET 'http://localhost:8081/JSON/context/view/contextList/' -k  --header 'Accept: application/json'
{"contextList":[]}
```
But within the same vpc if another request is initiated, a 503 response is obtained
Request and response 
```
curl --location --request GET 'https://stage.example.com/zap/JSON/context/view/contextList/' -k  --header 'Accept: application/json'

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
There isn't any flaw with the ingress and we have this ingress working for all other micro services and not working only for zap.

Attaching the service logs of this instance
```
172.0.58.108 - - [05/Jan/2024:12:53:24 +0000] "GET /zap/JSON/context/view/contextList/ HTTP/1.1" 503 190 "-" "curl/8.3.0" 232 0.010 [zap-zap-owasp-zap-8081] [] 172.0.66.42:8081 190 0.011 503 6bf5f814381bfbdc2fa2d6828213546c
172.0.58.108 - - [05/Jan/2024:12:53:25 +0000] "GET /zap/JSON/context/view/contextList/ HTTP/1.1" 503 190 "-" "curl/8.3.0" 232 0.008 [zap-zap-owasp-zap-8081] [] 172.0.66.42:8081 190 0.008 503 43ce7d40564a1fa6e4172a14631c6305
172.0.58.108 - - [05/Jan/2024:12:53:25 +0000] "GET /zap/JSON/context/view/contextList/ HTTP/1.1" 503 190 "-" "curl/8.3.0" 232 0.008 [zap-zap-owasp-zap-8081] [] 172.0.66.42:8081 190 0.008 503 c0288d6c1c0b5d7ea9dd52c2b56afc7a
172.0.58.108 - - [05/Jan/2024:12:53:26 +0000] "GET /zap/JSON/context/view/contextList/ HTTP/1.1" 503 190 "-" "curl/8.3.0" 232 0.008 [zap-zap-owasp-zap-8081] [] 172.0.66.42:8081 190 0.008 503 7c45cc00a6f51db0e2ac6f1522e1331e
172.0.58.108 - - [05/Jan/2024:12:53:26 +0000] "GET /zap/JSON/context/view/contextList/ HTTP/1.1" 503 190 "-" "curl/8.3.0" 232 0.018 [zap-zap-owasp-zap-8081] [] 172.0.66.42:8081 190 0.018 503 7b558ac21a243f40bb4995bc07b9a2f6
172.0.56.238 - - [05/Jan/2024:12:53:26 +0000] "GET /zap/JSON/context/view/contextList/ HTTP/1.1" 503 190 "-" "curl/8.3.0" 232 0.008 [zap-zap-owasp-zap-8081] [] 172.0.66.42:8081 190 0.008 503 45892918b52f3b0669eb9592dd29f42a
[eks-master@sbox-bastion ~]$ wl 
```

We have checked almost every other online resource and nothing has helped us until now. 

### Steps to reproduce the behavior

1. Create deployment
2. Create service
3. Create ingress

Run three type of curls
1. Within the VPC
2. Within the root
3. Within the instance

This does not work when we try it within the VPC

### Expected behavior

Input request which goes through the ingress
```
curl --location --request GET 'https://stage.example.com/zap/JSON/context/view/contextList/' -k  --header 'Accept: application/json'
{"contextList":[]}
```

### Software versions

ZAP 2.14.0

### Errors from the zap.log file

No errors as the request does not reach the instance. This is the logs of the application running on k8s.
```daemon] WARN  org.flywaydb.core.internal.database.base.Database - Flyway upgrade recommended: HSQLDB 2.7 is newer than this version of Flyway and support has not been tested. The latest supported version of HSQLDB is 2.6.
4475 [ZAP-daemon] INFO  org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Schema history table "PUBLIC"."flyway_schema_history" does not exist yet
4478 [ZAP-daemon] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.013s)
4485 [ZAP-daemon] INFO  org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table "PUBLIC"."flyway_schema_history" ...
4510 [ZAP-daemon] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "PUBLIC": << Empty Schema >>
4515 [ZAP-daemon] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "PUBLIC" to version "1 - Create table boast"
4532 [ZAP-daemon] INFO  org.flywaydb.core.internal.command.DbMigrate - Successfully applied 1 migration to schema "PUBLIC", now at version v1 (execution time 00:00.003s)
4538 [ZAP-daemon] INFO  org.zaproxy.addon.oast.services.callback.CallbackService - Started callback service on 0.0.0.0:35465
4542 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - Creating new root CA certificate.
5070 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - New root CA certificate created.
7108 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - ZAP is now listening on 0.0.0.0:8081

```

### Would you like to help fix this issue?

- [ ] Yes
