### ISSUE TITLE
When i start the zap proxy pods without doing any hit i can see that zap proxy tries hitting some random sites

### ISSUE THREAD

**Issue by kartikm0021** [zaproxy/zaproxy#8331]
### Describe the bug

When i try starting the zap proxy pods, i see this warning message . i am using the below image
image: ghcr.io/zaproxy/zaproxy:stable
i have no use case where i hit this url. But the funny part is this scanning starting happening when i start the pods.
 
WARN  org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler - An exception occurred while attempting to connect to: https://koko33.net/
The exception was:
Remote host terminated the handshake
Root cause:
EOFException: SSL peer shut down incorrectly
The following document may be of assistance in resolving this failure:
https://www.zaproxy.org/faq/how-to-connect-to-an-https-site-that-reports-a-handshake-failure/
264391 [ZAP-IO-Server-1-20030] INFO  org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec - Recoverable I/O exception (org.apache.hc.core5.http.NoHttpResponseException) caught when processing request to {s}->https://koko33.net:443
[266.038s][warning][os,thread] Attempt to protect stack guard pages failed (0x00007efb82077000-0x00007efb8207b000).

### Steps to reproduce the behavior

ispin my pods and then see this warning pop up
```
version: "3.8"

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    ports:
      - "8090:8090"
    command: zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.addrs.addr.name=".*" -config api.addrs.addr.regex=true -config api.key=g29fdi63l9hqdd3p0te8cupv0g -Xmx10g
    restart: always
    # volumes:
    #   - zap-data:/zap/wrk  # Mount ZAP work directory to volume
      
    environment:  # New section to set environment variable
      - ZAP_MAX_RESPONSE_BODY_SIZE=33554432  # Sets limit to 32 MB

    deploy:
      resources:
        limits:
          memory: "20g"
          cpus: "10"  
        reservations:
          memory: "10g"
          cpus: "3"  
```

### Expected behavior

the pod should not be trying to hit https://koko33.net/

### Software versions

ghcr.io/zaproxy/zaproxy:stable

### Would you like to help fix this issue?

- [X] Yes
