### ISSUE TITLE
AF Proxy support

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8360]
Add support to the Automation Framework for the outgoing proxy settings.
Proposed yaml:
```yaml
env:
  proxy:
    hostname:
    port:
    username:
    password:
    exclusions:  # List of excluded hosts
```
