### ISSUE TITLE
automation plan stuck for 10 minutes after succeeding

### ISSUE THREAD

**Issue by schdief** [zaproxy/zaproxy#8558]
### Describe the bug

we have been using ZAP for years now within our pipelines, so thanks a lot first, for providing us with that great tool :)

we use ZAP automation framework based on `softwaresecurityproject/zap-stable@sha256:39b1ebe74fba7f3048f6a6801c66b1d0f36dcc970813b65847a724ceb3837b94` and since Friday afternoon we got the error that our ajaxspider stopped finding any URLs - we didn't change the code or deployment between the failing and working run

we have the same issue across multiple teams using the same image

Friday afternoon:
```
2024-07-12T13:34:31.1654926Z Job spiderAjax started
2024-07-12T13:34:32.6742638Z Job spiderAjax test of type stats failed: At least X URLs found [0 < 1]
2024-07-12T13:34:32.6743715Z Job spiderAjax found 0 URLs
2024-07-12T13:34:32.6744659Z Job spiderAjax finished, time taken: 00:00:01
2024-07-12T13:34:32.6745531Z Automation plan failures:
2024-07-12T13:34:32.6746757Z 	Job spiderAjax test of type stats failed: At least X URLs found [0 < 1]
2024-07-12T13:34:37.8524455Z command terminated with exit code 1
```

Friday morning:
```
2024-07-12T12:51:39.5548182Z Job spiderAjax started
2024-07-12T12:52:01.3456881Z Job spiderAjax found 17 URLs
2024-07-12T12:52:01.3707154Z Job spiderAjax test of type stats passed: At least X URLs found [17 >= 1]
2024-07-12T12:52:01.3709140Z Job spiderAjax finished, time taken: 00:00:21
```

So we changed the test from ERROR to INFO so our pipelines continue working.
Then we noticed that the logfile couldn't be found anymore.

Friday afternoon:
```
mv: cannot stat '/home/zap/.ZAP/zap.log': No such file or directory
```

Friday morning:
```
(no output since mv just worked)
```

So we have removed the logfile archiving for now.
Now the run succeeds, but the automation plan is stuck for around 10 minutes after succeeding before it actually closes:

Today:
```
2024-07-16T05:17:00.5781117Z Automation plan succeeded!
2024-07-16T05:27:33.9067520Z 
```

Friday morning:
```
2024-07-12T12:52:53.9430976Z Automation plan succeeded!
2024-07-12T12:53:01.2595307Z 
```

I couldn't find any other issues and I couldn't find a new release, can you see the problem?

our automation plan:

```
env:
  contexts:
    - name: "parrot"                    # the name of the context
      urls:                               # a list of urls to attack
        - ${UATURL}
      includePaths:                       # optional list of paths that are in scope
        - "${UATURL}.*"
  parameters:
    failOnError: true
    failOnWarning: true
    progressToStdout: true
  vars: { }

jobs:
  - alertFilters:
      - ruleId: 10020
        ruleName: "Missing Anti-clickjacking Header"
        context: "parrot"
        newRisk: "False Positive" #RISK ACCEPTED BY RISK OWNER WITH GSN ID 12345
    type: "alertFilter"
    name: "alertFilter"
  - parameters:
      context: "parrot"
      maxDuration: 5
      maxDepth: 5
      maxChildren: 20
    type: "spider"
    name: "spider"
    tests:
      - onFail: "ERROR"
        statistic: "automation.spider.urls.added" # global
        operator: ">="
        value: 5
        type: "stats"
        name: "ZAP was able to reach the site(s)"
  - parameters:
      maxDuration: 10
      maxCrawlDepth: 10
      numberOfBrowsers: 1
      browserId: "firefox-headless"
      maxCrawlStates: 0
      eventWait: 2000
      reloadWait: 2000
      clickDefaultElems: true
      clickElemsOnce: true
      randomInputs: true
    type: "spiderAjax"
    name: "spiderAjax"
    tests:
      - onFail: "INFO"
        statistic: "spiderAjax.urls.added"
        operator: ">="
        value: 1
        type: "stats"
        name: "At least X URLs found"
  - parameters:
      maxDuration: 10
    type: "passiveScan-wait"
    name: "passiveScan-wait"
  - parameters:
      maxRuleDurationInMins: 10
      maxScanDurationInMins: 120
      delayInMs: 2
      injectPluginIdInHeader: true
    type: "activeScan"
    name: "activeScan"
  - parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk"
      reportFile: "zap-dast.json"
      reportTitle: "ZAP Report"
      reportDescription: ""
    type: "report"
    name: "report-json"
  - parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk"
      reportFile: "zap-dast.html"
      reportTitle: "ZAP Report"
      reportDescription: ""
    type: "report"
    name: "report-html"
```

### Steps to reproduce the behavior

use abovely mentioned image
use our automation plan
run it

### Expected behavior

ajayspider should find URLs like before
logfile should be provided as before
automation run should stop after succeding without failing

### Software versions

softwaresecurityproject/zap-stable@sha256:39b1ebe74fba7f3048f6a6801c66b1d0f36dcc970813b65847a724ceb3837b94

### Would you like to help fix this issue?

- [X] Yes
