### ISSUE TITLE
Adding a flag to enable/disable jobs in the automation plan

### ISSUE THREAD

**Issue by dossantospat** [zaproxy/zaproxy#8626]
### Is your feature request related to a problem? Please describe.

I'm writing a generic gitlab component for the Zap Automation Framework. I would like my component to allow users to enable or disable jobs as they wish.

However today, the only way to enable or disable a job is to edit the automation plan file. It would be nice to have a way to do this without having to generate a specific automation plan file for each need.

### Describe the solution you'd like

Adding a generic `enabled` key in the job parameters, or even better at the top level of each job, would suffice i think.
By default, the `enabled` would be true, to make sure things remain retro-compatible.

Something like this at the top level : 

```yaml
- type: spiderAjax
   enabled: true
   parameters:
     context:  #...                       
     user:       #...                     
     url:          #...  
```

or in the job parameters : 

```yaml
- type: spiderAjax
   parameters:
     enabled: true
     context: #...
     user:      #...                      
     url:         #... 
```

### Describe alternatives you've considered

The only alternative i found would be to generate an automation plan on the fly to add or remove jobs as wanted.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Note that there are 2 workarounds, for specific jobs.
In general the "import" jobs will not do anything if no relevant URLs are specified.
This should apply to:

- graphql
- openapi
- postman
- soap

Also the spiderAjax job has a `runOnlyIfModern` option which can be used to configure it to only run if the app appears to be a modern one.

Having said all that, I'm happy with the proposal to add an `enabled` flag - this can hopefully be added at a high level so that all jobs inherit it without having to be changed.

**Comment by psiinon** [comment]
@dossantospat would you like to implement this? 
If so we'll be very happy to provide advice and guidance...

**Comment by dossantospat** [comment]
@psiinon Why not ;). I cannot guarantee anything, since it would be on my free time. Any advice on where to start is welcome indeed

**Comment by kingthorin** [comment]
The best place to start is the Dev Guide 😄  https://www.zaproxy.org/docs/developer/

**Comment by dossantospat** [comment]
Hi,

I reviewed the code and here are my thoughts and questions regarding the addition of the 'enabled/disabled' flag for job automation.

I added an  `enabled ` flag to the automation plan at the same level as the job `name` or `type`. The idea is that any job can be disabled without forcing plugin authors to handle this field specifically :

```yaml
#...
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 16
    inScopeOnly: true
  name: "spiderAjax"
  type: "spiderAjax"
  enabled: false
```

From my understanding, even if a job is disabled, it still needs to be added to the plan in the  `AutomationPlan` class. It simply won't be executed when the plan is launched.

For the headless part, I think the behavior is fairly simple: if the  `enabled` flag is missing or set to  `true `, the job is executed. Otherwise, the job is not executed. This behavior is backward-compatible.

Things get more complicated with the graphical interface. Each add-on is responsible for displaying its own editing window, which means each job would need to add an  `enabled ` checkbox in its dialog. That said, this is already the case for other generic fields, like the  `name` for instance. I tested on one of the add-on, it's not that much work.

In the 'Automation' tab, I added an 'Enabled' column, which lets you see if a job is active or not. This helps in understanding why a job remains in the  `NOT STARTED` status when the plan is launched.

I have not yet written the unit tests or added the translation messages to the properties files. I’m first waiting for your suggestions regarding what I mentioned above and the answers to the following questions :

- Question 1: Should i create a PR to share the code, even if its a work in progress ?
- Question 2: Is the automation plan used elsewhere? Do I need to ensure the proper functioning of the 'enabled' flag elsewhere?
- Question 3: Should I add a specific log when a job is disabled, to inform the user that a job exists but is simply disabled?
- Question 4: Should i create a new execution status ? a "SKIPPED" status for when a job is listed in a plan, but disabled ?
- Question 5: How is the add-on update process handled if we need to add the 'enabled' checkbox in the graphical interface? Does each add-on author need to do it? Can I add it myself?
- Question 6: How should the translation files be updated? Should we manually insert the keys into all files, with the English value until someone translates them? (I can handle French if necessary :wink )

Sorry for the long post :smile:
