### ISSUE TITLE
spiderAjax is missing some endpoints of OWASP Juice Shop

### ISSUE THREAD

**Issue by jeremychoi** [zaproxy/zaproxy#8804]
### Describe the bug:

spiderAjax is missing some endpoints. Please see the test results with OWASP Juice Shop below.

### Steps to reproduce the behavior:

1. run Juiceshop 17.1.1

`$ podman run --rm -it -p 10.10.10.10:3000:3000 ghcr.io/jeremychoi/juice-shop:v17.1.1-amd64`

2. run a ZAP scan with the following automation framework configuration file. (note: host.containers.internal was used because I ran a scan in a container. It can be changed to 10.10.10.10)
```
env:
  contexts:
  - excludePaths: []
    includePaths:
    - http://host.containers.internal:3000.*
    - http://host.containers.internal:3000.*
    name: Default Context
    sessionManagement:
      method: cookie
      parameters: {}
    urls:
    - http://host.containers.internal:3000/
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
jobs:
- name: passiveScan-config
  parameters:
    enableTags: false
    maxAlertsPerRule: 10
    maxBodySizeInBytesToScan: 10000
    scanOnlyInScope: true
  rules:
  - id: 2
    threshold: 'off'
  - id: 10015  
    threshold: 'off'
  - id: 10027  
    threshold: 'off'
  - id: 10096  
    threshold: 'off'
  - id: 10024  
    threshold: 'off'
  - id: 10098  
    threshold: 'off'
  - id: 10023  
    threshold: 'off'
  - id: 10105  
    threshold: 'off'
  type: passiveScan-config
- name: requestor
  parameters:  
    user: ''
  request: 
  - name: Verify server availability
    url: http://host.containers.internal:3000
  type: requestor
- name: spider 
  parameters:
    context: Default Context
    maxDuration: 3
    url: http://host.containers.internal:3000
    user: ''
  type: spider
- name: spiderAjax
  parameters:  
    browserId: firefox-headless
    context: Default Context
    maxDuration: 5
    url: http://host.containers.internal:3000
    user: ''
  type: spiderAjax
- name: passiveScan-wait
  parameters: {}
  type: passiveScan-wait
- name: report
  parameters:
... snipped ...

```

### Expected behavior:

No missing endpoint should be expected. For example, the following endpoints are missed and should be crawled:

- /rest/products/1/reviews
  - note: this request is made when a user clicks each product that is created by default when a Juice shop app runs
- /api/SecurityAnswers, /api/Users
  - note: this request is made when a user clicks Account -> "not yet customer" -> "Register" 

Those endpoints above exist and can be found when a user manually explorers (e.g. using ZAP's manual explore feature). However, it was observed that automated scannings only detect: 

/api/
        "name": "http://host.containers.internal:3000/api/Challenges/",
        "name": "http://host.containers.internal:3000/api/Feedbacks/",
        "name": "http://host.containers.internal:3000/api/Quantitys/",
        "name": "http://host.containers.internal:3000/api/SecurityQuestions/",

/rest/
        "name": "http://host.containers.internal:3000/rest/admin/application-configuration",
        "name": "http://host.containers.internal:3000/rest/admin/application-version",
        "name": "http://host.containers.internal:3000/rest/captcha/",
        "name": "http://host.containers.internal:3000/rest/languages",
        "name": "http://host.containers.internal:3000/rest/memories/",
        "name": "http://host.containers.internal:3000/rest/products/search",
        "name": "http://host.containers.internal:3000/rest/user/login()",
        "name": "http://host.containers.internal:3000/rest/user/whoami",

### Software versions:

ZAP 2.15.0 ( addon updated)

### Would you like to help fix this issue?

- [x] Yes
