### ISSUE TITLE
Sites Tree export might create malformed YAML data

### ISSUE THREAD

**Issue by tenaz3** [zaproxy/zaproxy#8858]
### Describe the bug:

When exporting ZAP's SiteTree scan results to YAML format, some scans produce invalid YAML files. The issue occurs when node/data keys contain multiple lines. This causes YAML parsing to fail with the error: `YAMLException - can not read a block mapping entry; a multiline key may not be an implicit key.`

While this is technically a YAML specification limitation rather than a ZAP issue, it would be beneficial to enhance the export functionality to properly escape or handle special characters in keys. This would prevent downstream YAML parsing failures when users try to process the exported files.

### Steps to reproduce the behavior:

Create a simple unit test on `EximSiteNodeUnitTest.java`

```java
@Test
    void shouldHandleNodeNamesWithSpacesAndSpecialCharacters() {
        // Given
        String yamlStr =
                "- node: My example of breaking line\n" +
                        "  second line"
                        + "  url: https://www.example.com\n"
                        + "  method: GET\n"
                        + "  responseLength: 1234\n"
                        + "  statusCode: 200\n";

        // When
        List<?> list = (ArrayList<?>) yaml.load(yamlStr);
        EximSiteNode node = new EximSiteNode((LinkedHashMap<?, ?>) list.get(0));

        // Then
        assertThat(node.getNode(), is(equalTo("My example of breaking line\n  second line")));
        assertThat(node.getUrl(), is(equalTo("https://www.example.com")));
        assertThat(node.getMethod(), is(equalTo("GET")));
        assertThat(node.getResponseLength(), is(equalTo(1234)));
        assertThat(node.getStatusCode(), is(equalTo(200)));

        assertThat(node.getErrors().size(), is(equalTo(0)));
    }
```

The test result will be:

```
Expected: is "GET:My example of breaking line\n  second line"
     but: was "GET:My example of breaking line"
java.lang.AssertionError: 
Expected: is "GET:My example of breaking line\n  second line"
     but: was "GET:My example of breaking line"
```

The `YAMLException` you can reproduce: load a yaml file  using `js-yaml` lib
```yaml
- node: '3'
          url: https://example.com
          method: GET
          children: 
          - node: Example broken line
  second line
            url: https://example.com
            method: GET
            responseLength: 2
            statusCode: 200
```
```ts
 yaml.load(content);
```

### Expected behavior:

No invalid yaml files after exporting the SiteTree

### Software versions:

2.16.0

### Would you like to help fix this issue?

- [x] Yes
