### ISSUE TITLE
Automation framework: Exit status job does not take into account False Positive confidence

### ISSUE THREAD

**Issue by mxkrmp** [zaproxy/zaproxy#8875]
### Describe the bug:

The exit status job does not take into account alert filter job when error level is set to "high" and all alerts with risk "high" changed to "false positive".

### Steps to reproduce the behavior:

1. Create automation via UI or via yaml with alertFilter and exitStatus job with the following configuration:
```
jobs:
 # add jobs e.g. passiveScan-config
  - name: Alert Filters
    type: alertFilter
    alertFilters:
      - ruleId: 6
        ruleName: Path Traversal
        newRisk: False Positive
        url: <url>
        methods:
          - GET
    parameters:
      deleteGlobalAlerts: true
  - name: Fetch Open API
    type: openapi
    parameters:
      apiUrl: https://dev.connect.uni-eng.de/v3/api-docs
      targetUrl: https://dev.connect.uni-eng.de/
      context: Authentication Context
      user: produser
  # add jobs e.g. passiveScan or spider to get alerts
  - type: exitStatus
    parameters:
      errorLevel: High
      warnExitValue: 0
      errorExitValue: 1
```
2. Run automation to find alerts.
3. The found alert is filtered out and is not shown in alert tab (UI) or in report later on.
4.  Alerts of type "Path Traversal" will be changed to risk "False Positive"
5. Exit status fails with exit code 1 with message "An alert has been raised with a risk of at least: High"

### Expected behavior:

Exit status should take into account alert filters (or also global filters).

### Software versions:

ZAP Version 2.16.0
Automation Framework Version 0.47.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
The bug is in this code: https://github.com/zaproxy/zap-extensions/blob/main/addOns/automation/src/main/java/org/zaproxy/addon/automation/jobs/ExitStatusJob.java#L82-L97

I forgot that False Positives are flagged in the Confidence - we should check that and ignore any FP alerts. My bad!
I plan to look at this soon, unless anyone else wants to jump in and take it?

**Comment by lindeberg** [comment]
This still doesn't work for me. But I have the same problem when setting `newRisk` to `info` as well.

**Logs:**
```
Run zaproxy/action-af@4dd5346bd6603523068d5ecbf3a366f57cdc1890
  with:
    plan: ./zap-plan.yaml
    docker_name: ghcr.io/zaproxy/zaproxy:nightly
    cmd_options: -addonupdate -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta
/usr/bin/chmod a+w /runner/_work/project/project
/usr/local/bin/docker pull ghcr.io/zaproxy/zaproxy:nightly -q
ghcr.io/zaproxy/zaproxy:nightly
/usr/local/bin/docker run -v /runner/_work/project/project:/zap/wrk/:rw --network=host -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -e HTTP_PROXY -e HTTPS_PROXY -t ghcr.io/zaproxy/zaproxy:nightly zap.sh -cmd -autorun /zap/wrk/./zap-plan.yaml -addonupdate -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta
Found Java version 17.0.14
Available memory: 3149[2](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:2) MB
Using JVM args: -Xmx787[3](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:3)m
514 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /home/zap/.ZAP_D/config.xml
6[4](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:4)3 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/session
644 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/dirbuster
644 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/fuzzers
644 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/plugin
Apr 30, 202[5](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:5) 8:42:10 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Check for updates call failed
Check for updates call failed
Job alertFilter set ruleId = 90028
Job alertFilter set newRisk = False Positive
Job alertFilter set url = .*\/paymentinstruments$
Job alertFilter set urlRegex = true
Job openapi set apiUrl = https://project.com/openapi.json
Job activeScan set defaultStrength = high
Job activeScan set defaultThreshold = low
Job report set template = modern
Job report set reportDir = /zap/wrk/zap-reports/modern/
Job report set template = traditional-md
Job report set reportDir = /zap/wrk/
Job report set reportFile = zap-report.md
Job exitStatus set warnLevel = medium
Job exitStatus set errorLevel = medium
Job passiveScan-config started
Job passiveScan-config set rule 1001[7](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:7) threshold to OFF
Job passiveScan-config set rule 10020 threshold to OFF
Job passiveScan-config set rule 10021 threshold to OFF
Job passiveScan-config set rule 1003[8](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:8) threshold to OFF
Job passiveScan-config set rule 10055 threshold to OFF
Job passiveScan-config set rule [9](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:9)0004 threshold to OFF
Job passiveScan-config finished, time taken: 00:00:00
Job alertFilter started
Job: alertFilter Added global filter for alertId: 90028 new risk: False Positive
Job alertFilter finished, time taken: 00:00:00
Job script started
Job: script Start action: add
Job script finished, time taken: 00:00:00
Job script started
Job: script Start action: enable
Job script finished, time taken: 00:00:00
Job openapi started
Job openapi added 40 URLs
Job openapi finished, time taken: 00:00:02
Job activeScan started
Job activeScan set default strength to HIGH
Job activeScan set default threshold to LOW
Job activeScan set rule [10](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:10)104 threshold to OFF
Job activeScan set rule 10095 threshold to OFF
Job activeScan set rule 40019 threshold to OFF
Job activeScan set rule 40020 threshold to OFF
Job activeScan set rule 40021 threshold to OFF
Job activeScan set rule 40022 threshold to OFF
Job activeScan set rule 40024 threshold to OFF
Job activeScan finished, time taken: 00:04:53
Job passiveScan-wait started
Job passiveScan-wait finished, time taken: 00:00:00
Job report started
Job report generated report /zap/wrk/zap-reports/modern/2025-04-30-ZAP-Report-project.com.html
Job report finished, time taken: 00:00:00
Job report started
Job report generated report /zap/wrk/zap-report.md
Job report finished, time taken: 00:00:00
Job exitStatus started
An alert has been raised with a risk of at least: medium
Job exitStatus finished, time taken: 00:00:00
Automation plan failures:
	An alert has been raised with a risk of at least: medium
Error: ZAP exited with error: Error: The process '/usr/local/bin/docker' failed with exit code 1
```

**zap-plan.yaml:**
```
# ZAP Automation Framework Plan
# This file defines the automated security testing (DAST) workflow for the To Go API
# Docs(ZAP Automation Framework): https://www.zaproxy.org/docs/automate/automation-framework/

# Docs(env): https://www.zaproxy.org/docs/desktop/addons/automation-framework/environment/
env:
  # Contexts define the scope of the scan
  contexts:
    - name: API Context
      urls:
        - https://project.com/
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  # Docs(passiveScan-config): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-pscanconf/
  # FYI: Needs to be run before openapi/activeScan/passiveScan-wait
  - type: passiveScan-config
    rules:
      # https://www.zaproxy.org/docs/alerts/
      # Disable passive browser-specific rules
      # threshold: off means the rule is disabled — it won't trigger, scan, or generate any alerts.
      # NOTE: Passive rules have to be added both in passiveScan-config and alertFilter
      - id: 10017   # X-Permitted-Cross-Domain-Policies Header Missing
        threshold: off
      - id: 10020   # X-Frame-Options Header Not Set
        threshold: off
      - id: 10021 # X-Content-Type-Options Header Missing
        threshold: off
      - id: 10038   # Content Security Policy (CSP) Header Not Set
        threshold: off
      - id: 10055   # X-Content-Type-Options Header Missing
        threshold: off
      - id: 90004 # Insufficient Site Isolation Against Spectre Vulnerability (missing CORP-header)
        threshold: off # No risk since the API only serves mobile applications, not browsers.

  # Docs(alertFilter): https://www.zaproxy.org/docs/desktop/addons/alert-filters/automation/
  # FYI: Needs to be run before openapi/activeScan/passiveScan-wait
  # Modify the risk level of specific alerts, or dismiss with False Positive
  - type: alertFilter
    alertFilters:
      # https://www.zaproxy.org/docs/alerts/
      # Disable browser-specific rules
      - ruleId: 90028 # Insecure HTTP Method
        newRisk: False Positive
        url: '.*\/persons\/paymentinstruments$' # No risk since the endpoint is for authenticated accounts.
        urlRegex: true

  # OpenAPI Import: Import API definition from Swagger to understand API structure
  # Docs(openapi): https://www.zaproxy.org/docs/desktop/addons/openapi-support/automation/
  - type: openapi
    parameters:
      apiUrl: https://project.com/openapi.json
  
  # Active Scan: Actively probe the API for vulnerabilities
  # This sends potentially malicious payloads to test endpoints
  # Docs(activeScan): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-ascan/
  - type: activeScan
    policyDefinition:
      defaultStrength: high # How thorough the scan should be
      defaultThreshold: low
      rules:
        # https://www.zaproxy.org/docs/alerts/
        - id: 10104 # User Agent Fuzzer
          threshold: off
        - id: 10095 # Backup File Disclosure
          threshold: off # Many false positives. Low risk since the tech stack has no backup files on the server.
        - id: 40019 # SQL Injection - MySQL
          threshold: off
        - id: 40020 # SQL Injection - Hypersonic SQL
          threshold: off
        - id: 40021 # SQL Injection - Oracle
          threshold: off
        - id: 40022 # SQL Injection - PostgreSQL
          threshold: off
        - id: 40024 # SQL Injection - SQLite
          threshold: off

  # Docs(passiveScan-wait): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-pscanwait/
  # Passive scanning analyzes all HTTP requests made by the activeScan without sending additional requests
  - type: passiveScan-wait

  # Docs(report): https://www.zaproxy.org/docs/desktop/addons/report-generation/automation/
  - type: report
    parameters:
      template: modern
      # https://github.com/zaproxy/action-af?tab=readme-ov-file#files
      reportDir: /zap/wrk/zap-reports/modern/

  # This will be added to the GitHub Actions job summary
  # Docs(report): https://www.zaproxy.org/docs/desktop/addons/report-generation/automation/
  - type: report
    parameters:
      template: traditional-md
      # https://github.com/zaproxy/action-af?tab=readme-ov-file#files
      reportDir: /zap/wrk/
      reportFile: zap-report.md

  # Exit Status: Define scan success/failure criteria for CI/CD pipeline
  # This determines if the GitHub Action will pass or fail
  # Docs(exitStatus): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-exitstatus/
  - type: exitStatus
    parameters:
      warnLevel: medium # Fail if medium or high severity issues are found
      errorLevel: medium
```

**GitHub Action step:**
```yaml
      - name: ZAP Scan
        uses: zaproxy/action-af@4dd5346bd6603523068d5ecbf3a366f57cdc1890 # v0.2.0
        with:
          plan: ./zap-plan.yaml
          docker_name: ghcr.io/zaproxy/zaproxy:nightly
          # https://www.zaproxy.org/addons/
          # https://www.zaproxy.org/docs/desktop/start/features/addons/
          # https://www.zaproxy.org/docs/desktop/cmdline/
          # https://www.zaproxy.org/docs/automate/automation-framework/#updating-add-ons
          cmd_options: >-
            -addonupdate
            -addoninstall ascanrulesAlpha
            -addoninstall ascanrulesBeta
            -addoninstall pscanrulesAlpha
            -addoninstall pscanrulesBeta
        env:
          ZAP_AUTH_HEADER: Authorization-Token
          ZAP_AUTH_HEADER_VALUE: ${{ steps.auth.outputs.token }}
```
