### ISSUE TITLE
Alerts Summary reports on filtered alerts. Difference between 2.15.0 & 2.16.0

### ISSUE THREAD

**Issue by smilowski** [zaproxy/zaproxy#8888]
### Describe the bug:

We are using 2 API's in order to extract Alerts from ZAP via zap clientapi in JAVA

- org.zaproxy.clientapi.gen.Alert#alertsSummary
- org.zaproxy.clientapi.gen.Alert#alerts

We're also setting alert filters using the following API:

- org.zaproxy.clientapi.gen.AlertFilter#addAlertFilter

Up till ZAP v. 2.15.0 the alerts filtered ( with 'newlevel' set as FALSE_POSITIVE ) were filtered from output of 'alertsSummary' & 'alerts' API's. 

With ZAP v.2.16.0 the alerts are counted under summary under initial risk i.e. 'High'
Funnily enough they are not present on the reports.

### Steps to reproduce the behavior:

1. Apply Alert filter to modify Confidence to 'False Positive'
2. Start Active Scan with of an App where a **High** Alert will be generated. 
3. Call the **org.zaproxy.clientapi.gen.Alert#alertsSummary** API
4. The API provides a response with _{"alertsSummary":{"High":1,"Low":0,"Medium":0,"Informational":0}}_

### Expected behavior:

The API provides a response with _{"alertsSummary":{"High":0,"Low":0,"Medium":0,"Informational":0}}_

### Software versions:

{"version":"2.16.0"}

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
`Apply Alert filter to modify Confidence to 'False Positive'`
That changes the alerts that have already been raised, it will not necessarily affect new alerts.
Can you check to make sure that the alert filter is really changing the alerts?

**Comment by smilowski** [comment]
hi @psiinon 
Yup, it was the case till 2.15.0.
In our process, the the filters are applied before the scan takes place.

Here is the response from org.zaproxy.clientapi.gen.Alert#alerts on 2.15.0
![Image](https://github.com/user-attachments/assets/0029d4b7-abae-443d-84ab-7d06dd461e89)

Here is the response from 2.16.0 on exactly the same app, where exactly the same alert filters are applied
![Image](https://github.com/user-attachments/assets/463bd819-4697-44bc-887a-06d68dc39ae3)

As you can see the risk remains 'High' in 2.16.0. It is updated to 'Informational' on 2.15.0

**Comment by smilowski** [comment]
@thc202 Just tried it out with _zaproxy/zaproxy:20250311-weekly_
There is no change. The alert risk still remains _high_ as in 2.16.0

**Comment by kingthorin** [comment]
Please provide the script that is raising the alert.

**Comment by smilowski** [comment]
hi @kingthorin,

Here is a redacted version of the script. No magic, pretty basic authentication check.
```js
var RISK = 3
var CONFIDENCE = 2
var TITLE = "XXX - Unauthenticated endpoint"
var DESCRIPTION = "A potential data leakage is present in the application. The endpoint does not require authentication"
var SOLUTION = "Secure endpoint so that it can be accessed only by authenticated users"
var REFERENCE = "https://cwe.mitre.org/data/definitions/284.html"
var CWEID = 284 // CWE-284: Improper Access Control
var WASCID = 13 // WASC-13 - Information Leakage


// This method is called for every node on the site
// ARGS: ActiveScan as, HttpMessage msg
function scanNode(as, msg) {
    _logger("Scanning " + msg.getRequestHeader().getURI().toString());

    // Send a request without authorization header to check if access is allowed
    var msg_unauthenticated = msg.cloneRequest();
    msg_unauthenticated.getRequestHeader().setHeader("Authorization", null);
    msg_unauthenticated.getRequestHeader().setHeader("SCAN-XXX-UNAUTHENTICATED", "true");
    as.sendAndReceive(msg_unauthenticated);

    var code = msg_unauthenticated.getResponseHeader().getStatusCode()
    var isUnauthenticated = code !== 302 && (code >= 200 && code <= 400);
    if (isUnauthenticated && !isExcluded(msg_unauthenticated)) {
        raise_alert(msg_unauthenticated, as);
    }
}

function raise_alert(msg, as) {
    _logger("Vulnerability found, creating alert for: " + msg.getRequestHeader().getURI().toString())
    as.newAlert()
        .setRisk(RISK)
        .setConfidence(CONFIDENCE)
        .setName(TITLE)
        .setDescription(DESCRIPTION)
        .setParam(msg.getRequestHeader().getURI().toString())
        .setEvidence("")
        .setSolution(SOLUTION)
        .setReference(REFERENCE)
        .setCweId(CWEID)
        .setWascId(WASCID)
        .setMessage(msg)
        .raise();
}

function isExcluded(msg) {
    "**REDACTED_INTERNAL_LOGIC**"
    return false;
}

function _logger() {
    print("[" + this["zap.script.name"] + "] " + arguments[0]);
}

String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
};
```

**Comment by kingthorin** [comment]
Thanks, I just wanted to test a few things when I realized it was a script rule.

**Comment by kingthorin** [comment]
Could you add a screenshot of the filter config?

**Comment by thc202** [comment]
This is no an add-on issue.

**Comment by lindeberg** [comment]
I'm having this problem.

**Logs:**
```
Run zaproxy/action-af@4dd5346bd6603523068d5ecbf3a366f57cdc1890
  with:
    plan: ./zap-plan.yaml
    docker_name: ghcr.io/zaproxy/zaproxy:nightly
    cmd_options: -addonupdate -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta
/usr/bin/chmod a+w /runner/_work/project/project
/usr/local/bin/docker pull ghcr.io/zaproxy/zaproxy:nightly -q
ghcr.io/zaproxy/zaproxy:nightly
/usr/local/bin/docker run -v /runner/_work/project/project:/zap/wrk/:rw --network=host -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -e HTTP_PROXY -e HTTPS_PROXY -t ghcr.io/zaproxy/zaproxy:nightly zap.sh -cmd -autorun /zap/wrk/./zap-plan.yaml -addonupdate -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta
Found Java version 17.0.14
Available memory: 3149[2](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:2) MB
Using JVM args: -Xmx787[3](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:3)m
514 [main] INFO  org.parosproxy.paros.Constant - Copying default configuration to /home/zap/.ZAP_D/config.xml
6[4](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:4)3 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/session
644 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/dirbuster
644 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/fuzzers
644 [main] INFO  org.parosproxy.paros.Constant - Creating directory /home/zap/.ZAP_D/plugin
Apr 30, 202[5](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:5) 8:42:10 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Check for updates call failed
Check for updates call failed
Job alertFilter set ruleId = 90028
Job alertFilter set newRisk = False Positive
Job alertFilter set url = .*\/paymentinstruments$
Job alertFilter set urlRegex = true
Job openapi set apiUrl = https://project.com/openapi.json
Job activeScan set defaultStrength = high
Job activeScan set defaultThreshold = low
Job report set template = modern
Job report set reportDir = /zap/wrk/zap-reports/modern/
Job report set template = traditional-md
Job report set reportDir = /zap/wrk/
Job report set reportFile = zap-report.md
Job exitStatus set warnLevel = medium
Job exitStatus set errorLevel = medium
Job passiveScan-config started
Job passiveScan-config set rule 1001[7](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:7) threshold to OFF
Job passiveScan-config set rule 10020 threshold to OFF
Job passiveScan-config set rule 10021 threshold to OFF
Job passiveScan-config set rule 1003[8](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:8) threshold to OFF
Job passiveScan-config set rule 10055 threshold to OFF
Job passiveScan-config set rule [9](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:9)0004 threshold to OFF
Job passiveScan-config finished, time taken: 00:00:00
Job alertFilter started
Job: alertFilter Added global filter for alertId: 90028 new risk: False Positive
Job alertFilter finished, time taken: 00:00:00
Job script started
Job: script Start action: add
Job script finished, time taken: 00:00:00
Job script started
Job: script Start action: enable
Job script finished, time taken: 00:00:00
Job openapi started
Job openapi added 40 URLs
Job openapi finished, time taken: 00:00:02
Job activeScan started
Job activeScan set default strength to HIGH
Job activeScan set default threshold to LOW
Job activeScan set rule [10](https://github.com/company/project/actions/runs/14750427193/job/41406403845#step:5:10)104 threshold to OFF
Job activeScan set rule 10095 threshold to OFF
Job activeScan set rule 40019 threshold to OFF
Job activeScan set rule 40020 threshold to OFF
Job activeScan set rule 40021 threshold to OFF
Job activeScan set rule 40022 threshold to OFF
Job activeScan set rule 40024 threshold to OFF
Job activeScan finished, time taken: 00:04:53
Job passiveScan-wait started
Job passiveScan-wait finished, time taken: 00:00:00
Job report started
Job report generated report /zap/wrk/zap-reports/modern/2025-04-30-ZAP-Report-project.com.html
Job report finished, time taken: 00:00:00
Job report started
Job report generated report /zap/wrk/zap-report.md
Job report finished, time taken: 00:00:00
Job exitStatus started
An alert has been raised with a risk of at least: medium
Job exitStatus finished, time taken: 00:00:00
Automation plan failures:
	An alert has been raised with a risk of at least: medium
Error: ZAP exited with error: Error: The process '/usr/local/bin/docker' failed with exit code 1
```

**zap-plan.yaml:**
```yaml
# ZAP Automation Framework Plan
# This file defines the automated security testing (DAST) workflow for the API
# Docs(ZAP Automation Framework): https://www.zaproxy.org/docs/automate/automation-framework/

# Docs(env): https://www.zaproxy.org/docs/desktop/addons/automation-framework/environment/
env:
  # Contexts define the scope of the scan
  contexts:
    - name: API Context
      urls:
        - https://project.com/
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  # Docs(passiveScan-config): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-pscanconf/
  # FYI: Needs to be run before openapi/activeScan/passiveScan-wait
  - type: passiveScan-config
    rules:
      # https://www.zaproxy.org/docs/alerts/
      # Disable passive browser-specific rules
      # threshold: off means the rule is disabled — it won't trigger, scan, or generate any alerts.
      # NOTE: Passive rules have to be added both in passiveScan-config and alertFilter
      - id: 10017   # X-Permitted-Cross-Domain-Policies Header Missing
        threshold: off
      - id: 10020   # X-Frame-Options Header Not Set
        threshold: off
      - id: 10021 # X-Content-Type-Options Header Missing
        threshold: off
      - id: 10038   # Content Security Policy (CSP) Header Not Set
        threshold: off
      - id: 10055   # X-Content-Type-Options Header Missing
        threshold: off
      - id: 90004 # Insufficient Site Isolation Against Spectre Vulnerability (missing CORP-header)
        threshold: off # No risk since the API only serves mobile applications, not browsers.

  # Docs(alertFilter): https://www.zaproxy.org/docs/desktop/addons/alert-filters/automation/
  # FYI: Needs to be run before openapi/activeScan/passiveScan-wait
  # Modify the risk level of specific alerts, or dismiss with False Positive
  - type: alertFilter
    alertFilters:
      # https://www.zaproxy.org/docs/alerts/
      # Disable browser-specific rules
      - ruleId: 90028 # Insecure HTTP Method
        newRisk: False Positive
        url: '.*\/persons\/paymentinstruments$' # No risk since the endpoint is for authenticated accounts.
        urlRegex: true

  # OpenAPI Import: Import API definition from Swagger to understand API structure
  # Docs(openapi): https://www.zaproxy.org/docs/desktop/addons/openapi-support/automation/
  - type: openapi
    parameters:
      apiUrl: https://project.com/openapi.json
  
  # Active Scan: Actively probe the API for vulnerabilities
  # This sends potentially malicious payloads to test endpoints
  # Docs(activeScan): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-ascan/
  - type: activeScan
    policyDefinition:
      defaultStrength: high # How thorough the scan should be
      defaultThreshold: low
      rules:
        # https://www.zaproxy.org/docs/alerts/
        - id: 10104 # User Agent Fuzzer
          threshold: off
        - id: 10095 # Backup File Disclosure
          threshold: off # Many false positives. Low risk since the tech stack has no backup files on the server.
        - id: 40019 # SQL Injection - MySQL
          threshold: off
        - id: 40020 # SQL Injection - Hypersonic SQL
          threshold: off
        - id: 40021 # SQL Injection - Oracle
          threshold: off
        - id: 40022 # SQL Injection - PostgreSQL
          threshold: off
        - id: 40024 # SQL Injection - SQLite
          threshold: off

  # Docs(passiveScan-wait): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-pscanwait/
  # Passive scanning analyzes all HTTP requests made by the activeScan without sending additional requests
  - type: passiveScan-wait

  # Docs(report): https://www.zaproxy.org/docs/desktop/addons/report-generation/automation/
  - type: report
    parameters:
      template: modern
      # https://github.com/zaproxy/action-af?tab=readme-ov-file#files
      reportDir: /zap/wrk/zap-reports/modern/

  # This will be added to the GitHub Actions job summary
  # Docs(report): https://www.zaproxy.org/docs/desktop/addons/report-generation/automation/
  - type: report
    parameters:
      template: traditional-md
      # https://github.com/zaproxy/action-af?tab=readme-ov-file#files
      reportDir: /zap/wrk/
      reportFile: zap-report.md

  # Exit Status: Define scan success/failure criteria for CI/CD pipeline
  # This determines if the GitHub Action will pass or fail
  # Docs(exitStatus): https://www.zaproxy.org/docs/desktop/addons/automation-framework/job-exitstatus/
  - type: exitStatus
    parameters:
      warnLevel: medium # Fail if medium or high severity issues are found
      errorLevel: medium
```

**GitHub Action step:**
```yaml
      - name: ZAP Scan
        uses: zaproxy/action-af@4dd5346bd6603523068d5ecbf3a366f57cdc1890 # v0.2.0
        with:
          plan: ./zap-plan.yaml
          docker_name: ghcr.io/zaproxy/zaproxy:nightly
          # https://www.zaproxy.org/addons/
          # https://www.zaproxy.org/docs/desktop/start/features/addons/
          # https://www.zaproxy.org/docs/desktop/cmdline/
          # https://www.zaproxy.org/docs/automate/automation-framework/#updating-add-ons
          cmd_options: >-
            -addonupdate
            -addoninstall ascanrulesAlpha
            -addoninstall ascanrulesBeta
            -addoninstall pscanrulesAlpha
            -addoninstall pscanrulesBeta
        env:
          ZAP_AUTH_HEADER: Authorization-Token
          ZAP_AUTH_HEADER_VALUE: ${{ steps.auth.outputs.token }}
```
