### ISSUE TITLE
Insufficient Site Isolation Against Spectre Vulnerability: Cross-Origin-Embedder-Policy header is already set to 'require-corp'

### ISSUE THREAD

**Issue by Macleykun** [zaproxy/zaproxy#8908]
### Describe the bug:

Hello!

I think this may be a bug, as i verfied the header is correctly set.
But when i visit: https://rockraiders.rocks/sitemap.xml and look at the Response Headers i notice these are set:
```
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-site
```

I use this github action to do the scan: https://github.com/zaproxy/action-full-scan and it's configured to be on the latest version:

```
name: Full OWASP web security scan
on:
  schedule:
    - cron: '0 0 * * wed' # Every wednesday at 00:05 UTC
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan our website
    steps:
      - name: Get the ignore issues list
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://rockraiders.rocks'
          rules_file_name: '.github/.zap/rules.tsv'
```

It reports that the sitemap.xml isn't returning the right headers but I do believe it does:

![Image](https://github.com/user-attachments/assets/a1581d68-89ee-40e3-9213-63ce44b2f125)

This is the full javascript worker that handles the headers:
```js
export default {
  async fetch(request) {
    const DEFAULT_SECURITY_HEADERS = {
      /*
    Secure your application with Content-Security-Policy headers.
    Enabling these headers will permit content from a trusted domain and all its subdomains.
    @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
    "Content-Security-Policy": "default-src 'self' example.com *.example.com",
    */
//UNCOMMENT    "Content-Security-Policy": "default-src 'none'; style-src 'self' 'sha256-4Su6mBWzEIFnH4pAGMOuaeBrstwJN4Z3pq/s1Kn4/KQ=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-p08VBe6m5i8+qtXWjnH/AN3klt1l4uoOLsjNn8BjdQo='; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; script-src 'self'; img-src 'self' data:;",
      /*
    You can also set Strict-Transport-Security headers.
    These are not automatically set because your website might get added to Chrome's HSTS preload list.
    Here's the code if you want to apply it:
    "Strict-Transport-Security" : "max-age=63072000; includeSubDomains; preload",
    */
    "Strict-Transport-Security" : "max-age=63072000; includeSubDomains; preload",
      /*
    Permissions-Policy header provides the ability to allow or deny the use of browser features, such as opting out of FLoC - which you can use below:
    "Permissions-Policy": "interest-cohort=()",
    */
    "Permissions-Policy": "interest-cohort=()",
      /*
    X-XSS-Protection header prevents a page from loading if an XSS attack is detected.
    @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
    */
    "X-XSS-Protection": "0",
      /*
    X-Frame-Options header prevents click-jacking attacks.
    @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
    */
      "X-Frame-Options": "DENY",
      /*
    X-Content-Type-Options header prevents MIME-sniffing.
    @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
    */
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "strict-origin-when-cross-origin",
      "Cross-Origin-Embedder-Policy": 'require-corp',
      "Cross-Origin-Opener-Policy": 'same-origin',
      "Cross-Origin-Resource-Policy": 'same-site',
      "access-control-allow-origin": "https://rockraiders.rocks", // for llr.researchrealm.net change the name for that in a seperate worker
    };
    const BLOCKED_HEADERS = [
      "Public-Key-Pins",
      "X-Powered-By",
      "X-AspNet-Version",
    ];

    let response = await fetch(request);
    let newHeaders = new Headers(response.headers);

    const tlsVersion = request.cf.tlsVersion;
    console.log(tlsVersion);
    // This sets the headers for HTML responses:
    if (
      newHeaders.has("Content-Type") &&
      !newHeaders.get("Content-Type").includes("text/html")
    ) {
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: newHeaders,
      });
    }

    Object.keys(DEFAULT_SECURITY_HEADERS).map((name) => {
      newHeaders.set(name, DEFAULT_SECURITY_HEADERS[name]);
    });

    BLOCKED_HEADERS.forEach((name) => {
      newHeaders.delete(name);
    });

    if (tlsVersion !== "TLSv1.2" && tlsVersion !== "TLSv1.3") {
      return new Response("You need to use TLS version 1.2 or higher.", {
        status: 400,
      });
    } else {
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: newHeaders,
      });
    }
  },
};
```
Source: https://developers.cloudflare.com/rules/snippets/examples/security-headers/

I'm terribly sorry if the issue is on my side and that i misunderstood something, but i've checked everything and i think the right response is returned.

### Steps to reproduce the behavior:

1. Configure the github action so it can run:
```
name: Full OWASP web security scan
on:
  schedule:
    - cron: '0 0 * * wed' # Every wednesday at 00:05 UTC
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan our website
    steps:
      - name: Get the ignore issues list
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://rockraiders.rocks'
#          rules_file_name: '.github/.zap/rules.tsv'
```
2. Run the action, and wait for the report to be generated.
3. Open the report and view that the Insufficient Site Isolation Against Spectre Vulnerability is applicable on https://rockraiders.rocks/sitemap.xml .

### Expected behavior:

The scan should determin that the headers are set correctly and thus not report on it.

### Software versions:

zaproxy/action-full-scan@v0.12.0
https://github.com/zaproxy/action-full-scan/releases/tag/v0.12.0

### Screenshots:

![Image](https://github.com/user-attachments/assets/4651b2bb-c984-420e-9c5e-eeef165699f3)

![Image](https://github.com/user-attachments/assets/ff517edd-7176-4631-b7aa-4d154c5fa2be)

### Errors from the zap.log file:

[logs_36316524647.zip](https://github.com/user-attachments/files/19489040/logs_36316524647.zip)

### Additional context:

I do run behind CloudFlare and use the pages feature/JAM-stack, but i am able to control the headers.

### Would you like to help fix this issue?

- [x] Yes
